core_common_index:
    pattern:  /
    schemes:  [http]
    defaults: { _controller: CoreCommonBundle:Pages:index }

core_common_ajax_entity:
    pattern:  /admin/ajax/entity/get/data
    defaults: { _controller: CoreCommonBundle:AjaxEntity:getData }

core_common_ajax_entity_frontend:
    pattern: /ajax/search.json
    schemes:  [http]
    defaults: { _controller: CoreCommonBundle:AjaxEntity:getData }

auth_receiver:
    pattern:  /auth/receiver.html
    schemes:  [http]
    defaults: { _controller: CoreCommonBundle:Pages:receiver }


#экранируем, чтобы по прямой ссылке страницы не были доступны
#core_common_error404:
#    pattern:  /error404.html
#    defaults: { _controller: CoreCommonBundle:Pages:error404 }
#
#core_common_error503:
#    pattern:  /error503.html
#    defaults: { _controller: CoreCommonBundle:Pages:error503 }
#
#core_common_error504:
#    pattern:  /error504.html
#    defaults: { _controller: CoreCommonBundle:Pages:error504 }


#trouble_ticket_contact:
#    path:      /contacts.html
#    schemes:  [http]
#    defaults:  { _controller: CoreTroubleTicketBundle:TroubleTicket:contact }

