<?php

namespace Core\PaymentBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PaymentSystemController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\PaymentBundle\Controller\PaymentSystemController();
        return $instance;
    }
}
