<?php

namespace Core\ManufacturerBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BrandAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\ManufacturerBundle\Controller\Admin\BrandAdminController();
        return $instance;
    }
}
