<?php

namespace Core\OrderBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class OrderAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\OrderBundle\Controller\Admin\OrderAdminController();
        return $instance;
    }
}
