<?php

namespace Core\FaqBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FaqAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\FaqBundle\Controller\Admin\FaqAdminController();
        return $instance;
    }
}
