<?php

namespace Core\ProductBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProductModificationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\ProductBundle\Controller\ProductModificationController();
        return $instance;
    }
}
