trouble_ticket_index:
    path:      /index-{owner}.html
    schemes:  [http]
    defaults:  { _controller: CoreTroubleTicketBundle:TroubleTicket:index }
trouble_ticket_index_auth:
    path:      /index.html
    schemes:  [http]
    defaults:  { _controller: CoreTroubleTicketBundle:TroubleTicket:index }
trouble_ticket_log:
    path:      /log/{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreTroubleTicketBundle:TroubleTicket:log }

trouble_ticket_contact:
    path:      /contacts.html
    schemes:  [http]
    defaults:  { _controller: CoreTroubleTicketBundle:TroubleTicket:contact }

trouble_ticket_edit:
    path:      /edit-{hash}.html
    schemes:  [http]
    defaults:  { _controller: CoreTroubleTicketBundle:TroubleTicket:edit }
    schemes:  [http]
trouble_ticket_read:
    path:      /read-{hash}.html
    schemes:  [http]
    defaults:  { _controller: CoreTroubleTicketBundle:AjaxTroubleTicket:read }
trouble_ticket_close:
    path:      /close-{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreTroubleTicketBundle:AjaxTroubleTicket:close }