services:
# Админские сервисы
  core_manufacturer_admin:
    class: Core\ManufacturerBundle\Admin\ManufacturerAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, group: Продукция, label: Производители }
    arguments: [null, Core\ManufacturerBundle\Entity\Manufacturer, null ]

  #админский клас для сертификатов
  core_manufacturer_certificate_admin:
    class: Core\ManufacturerBundle\Admin\CertificateAdmin
    tags:
    - { name: sonata.admin,  manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore, label: Сертификаты производителей }
    arguments: [null, Core\ManufacturerBundle\Entity\Certificate, null]

  #админский клас для редактирования
  core_manufacturer_series_admin:
    class: Core\ManufacturerBundle\Admin\SeriesAdmin
    tags:
    - { name: sonata.admin,  manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, show_in_dashboard: false }
    arguments: [null, Core\ManufacturerBundle\Entity\Series, null]

   # редактирование в админке брендов
  core_manufacturer_brand_admin:
    class: Core\ManufacturerBundle\Admin\BrandAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, group: Продукция, label: Бренды }
    arguments: [null, Core\ManufacturerBundle\Entity\Brand, CoreManufacturerBundle:Admin\BrandAdmin ]