services:
  #админсике классы для баннеров
  core_banner_admin:
    class: Core\BannerBundle\Admin\BannerAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore,  group: Материалы, label: Баннеры }
    arguments: [null, Core\BannerBundle\Entity\CommonBanner, null]
    calls:
    - [ setSubClasses, [ { "Графический баннер": Core\BannerBundle\Entity\ImageBanner, "Flash баннер": Core\BannerBundle\Entity\FlashBanner, "Баннер по коду": Core\BannerBundle\Entity\CodeBanner} ] ]


  # логика для баннеров
  core_banner_logic:
    class: Core\BannerBundle\Logic\BannerLogic
    arguments: ['@router', '@doctrine.orm.entity_manager', '@service_container', '@application_knp_paginator_logic']

  # форма для изображений
  core_banner_image_form:
      class: Core\BannerBundle\Form\Type\ImageBannerFormType
      arguments: ['@doctrine.orm.entity_manager', '@security.context', '@session', '@request_stack']
      tags:
        - {name: form.type, alias: 'image_banner_form'}

  # форма для flash
  core_banner_flash_form:
      class: Core\BannerBundle\Form\Type\FlashBannerFormType
      arguments: ['@doctrine.orm.entity_manager', '@security.context', '@session', '@request_stack']
      tags:
        - {name: form.type, alias: 'flash_banner_form'}

  # форма для html etc.
  core_banner_code_form:
      class: Core\BannerBundle\Form\Type\CodeBannerFormType
      arguments: ['@doctrine.orm.entity_manager', '@security.context', '@session', '@request_stack']
      tags:
        - {name: form.type, alias: 'code_banner_form'}
  core_banner_entity_form:
     class: Core\BannerBundle\Form\Type\BannerEntityFormType
     arguments: ["@doctrine.orm.entity_manager"]
     tags:
     - { name: form.type, alias: banner_entity }