default:
    autoload:
           '': %paths.base%/src
    extensions:
        #расширение для Symfony2, чтобы файлы падали в папку бандла + возможность запуска по имени бандла
        Behat\Symfony2Extension:
            kernel:
                env: test
                debug: true
        #расширение для Symfony2, чтобы файлы падали в папку бандла + возможность запуска по имени бандла
        Behat\MinkExtension:
            base_url: 'http://www.olikids-sam.ru.vm/app_test.php/'
            #браузер, Который будет ходить по страничкам chrome|firefox
            browser_name: firefox
            #Сервер для тестов Mink, Можно настроить другие вроде sahi, goutte
            selenium2: ~
            goutte:
                guzzle_parameters:
                    curl.options:
                       CURLOPT_SSL_VERIFYPEER: false
                       CURLOPT_CERTINFO: false
                       CURLOPT_TIMEOUT: 120
                    ssl.certificate_authority: false