imports:
    - { resource: config.yml }

monolog:
    handlers:
        applog:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
        main:
            type: fingers_crossed
            action_level: debug
            handler: file
        file:
            type: stream
            level: error
        syslog:
            type: syslog
            level: error