imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: error
