imports:
    - { resource: config.yml }


monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: notice
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:         swift_mailer
#            formatter:    html_log_formatter
            content_type: text/html
            from_email:   %default_email%
            to_email:     %default_email%
            subject:      "Ошибка на сервере  promomaster.net"
            level:        critical
        mail:
            type: fingers_crossed
            action_level: critical
            handler: swift

