<?php

namespace Application\Sonata\UserBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AjaxContragentAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Application\Sonata\UserBundle\Controller\Admin\AjaxContragentAdminController();
        return $instance;
    }
}
