<?php

namespace Core\UnionBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UnionAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\UnionBundle\Controller\Admin\UnionAdminController();
        return $instance;
    }
}
