<?php

namespace Core\CategoryBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CategoryController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\CategoryBundle\Controller\CategoryController();
        return $instance;
    }
}
