<?php

namespace Core\ColorBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ColorAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\ColorBundle\Controller\Admin\ColorAdminController();
        return $instance;
    }
}
