<?php

namespace Core\FileBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AjaxFileController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\FileBundle\Controller\AjaxFileController();
        return $instance;
    }
}
