<?php

namespace Core\SiteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SectionCabinetController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\SiteBundle\Controller\SectionCabinetController();
        return $instance;
    }
}
