<?php

namespace JMS\I18nRoutingBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RedirectController__JMSInjector
{
    public static function inject($container) {
        $instance = new \JMS\I18nRoutingBundle\Controller\RedirectController();
        return $instance;
    }
}
