<?php

namespace Shtumi\UsefulBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AjaxAutocompleteJSONController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Shtumi\UsefulBundle\Controller\AjaxAutocompleteJSONController();
        return $instance;
    }
}
