#example:
#    full_options: { route: route_name, roles: [role1, role2], delimiters: [before, after] }

Материалы:
    Баннеры:                            { route: admin_core_banner_commonbanner_list }
    Площадки:                            { route: admin_core_site_commonsite_list }
    Размеры рекламных мест:                  { route: admin_core_directory_adplacesize_list }
    Рекламные места:                  #{ route: admin_core_site_adplace_list }
      Места:                            { route: admin_core_site_adplace_list }
      Стоимость:                           { route: admin_core_site_adplaceprice_list }
      #Скидки:                        { route: admin_core_site_adplacepricediscount_list }
    Разделы рекламных мест:            { route: admin_core_site_section_list }
    Рекламные компании:             { route: admin_core_adcompany_adcompany_list }
    Размещения:                       { route: admin_core_adcompany_placement_list }
    Банеры размещения:                       { route: admin_core_adcompany_placementbanner_list }
    Категории сайтов:                  { route: admin_core_category_sitecategory_list}

Пользователи:
    Контрагенты:                        { route: admin_sonata_user_commoncontragent_list }
    Пользователи:                       { route: admin_sonata_user_user_list }
    Группы:                             { route: admin_sonata_user_group_list }
    Траблтикеты:                        { route: admin_core_troubleticket_troubleticket_list }
    Категории траблтикетов:             { route: admin_core_category_troubleticketcategory_list }
#Продукция:
#    Продукция:                          { route: admin_core_product_commonproduct_list }
#    Анализ прайсов:                     { route: admin_core_logistics_supplierpriceanalysis_list }
#    Категории продукции:                { route: admin_core_category_productcategory_list }
#    Виртульные категории:               { route: admin_core_category_productvirtualcategory_list }
#    Характеристики:                     { route: admin_core_property_property_list }
#    Производители:                      { route: admin_core_manufacturer_manufacturer_list }
#    Сертификаты производителей:         { route: admin_core_manufacturer_certificate_list }
#    Бренды:                             { route: admin_core_manufacturer_brand_list }
#    Отзывы о товарах:                   { route: admin_core_review_review_list }
Бухгалтерия:
#    Заказы:                             { route: admin_core_order_order_list }
#
#    Предзаказы:                         { route: admin_core_order_preorder_preorder_list }
#    Незавершенные заказы:               { route: admin_core_statistics_notfinishedorder_list }
    Платежи:                            { route: admin_core_payment_payment_list, delimiters: [after] }
#    Продавцы:                           { route: admin_core_logistics_seller_list }
#    Поставщики:                         { route: admin_core_logistics_supplier_list, delimiters: [after] }
#    Поставки:                           { route: admin_core_logistics_supply_list }
#    Транзиты:                           { route: admin_core_logistics_transit_list }
#    Товар со всех складов:              { route: admin_core_logistics_unitinstock_list }
#    Склады:                             { route: admin_core_logistics_stock_list }
FAQ:
    Категории:                          { route: admin_core_category_faqcategory_list}
    Статьи:                             { route: admin_core_faq_article_list}
Системное:
    Гео данные:
        Мировые разделы:                {route: admin_core_directory_worldsection_list}
        Страны:                         { route: admin_core_directory_country_list }
        Регионы:                        { route: admin_core_directory_region_list }
        Города:                         { route: admin_core_directory_city_list }
    Финансовые настройки:
#        Справочник банков:              { route: admin_core_logistics_bank_list }
        Валюты:                         { route: admin_core_directory_currency_list }
#        Правовые формы:                 { route: admin_core_directory_legalform_list }
        Платежные системы:              { route: admin_core_payment_paymentsystem_commonpaymentsystem_list }
    Пременные для сайта:
        Настройки:                      { route: admin_core_config_config_list }
        Группы для настроек:            { route: admin_core_config_group_list }
        Цвета:                          { route: admin_core_color_color_list }
    Статусы:
#        Доп. статусы заказов:           { route: admin_core_order_extrastatus_list }
#        Статусы Предзаказов:            { route: admin_core_order_preorder_preorderstatus_list }
#        Причины списания:               { route: admin_core_logistics_unitinstockdefectreason_list }
#        Причины отмены заказов:         { route: admin_core_order_canceledreason_list }
#        Типы расходов поставки:         { route: admin_core_logistics_additionalcoststypeofsupply_list }
#        Статусы транзитов:              { route: admin_core_logistics_transitstatus_list }
#        Статусы поставок:               { route: admin_core_logistics_supplystatus_list }
        Статусы траблтикетов:           { route: admin_core_troubleticket_status_list }
        Приоритеты траблтикетов:        { route: admin_core_troubleticket_priority_list }
    Справочники:
        Единицы измерения:              { route: admin_core_directory_unitofmeasure_list }
        Группы для единиц измерения:    { route: admin_core_directory_unitofmeasuregroup_list }
    Видео-Хостинги:                     { route: admin_core_directory_videohosting_list }
    Праздники:                          { route: admin_core_holiday_holiday_list }
    Производственный календарь:         { route: : admin_core_officeworktime_schedule_list }
    Ценовые модели:                     { route: : admin_core_directory_pricemodel_list }
#Скидки:
#    Скидки по брендам:                  { route: admin_core_discounts_manufacturerdiscount_list }
#    Индивидуальные cкидки по брендам:   { route: admin_core_discounts_contragentmanufacturerdiscount_list }
#Доставка:
#    Компании:                           { route: admin_core_delivery_company_list }
#    Способы доставки:                   { route: admin_core_delivery_service_list }
#    Пункты выдачи:                      { route: admin_core_delivery_address_list }
#    Типы доставок:                      { route: admin_core_delivery_servicetype_list }
#Статистика:
#    Статистика по продуктам:            { route: admin_core_statistics_statistics_list }
