services:
  #сервис для редактирования банков
  core_logistics_bank_admin:
    class: Core\LogisticsBundle\Admin\BankAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, group: Бухгалтерия, label: "Справочник банков" }
    arguments: [null, Core\LogisticsBundle\Entity\Bank, null]

  #сервис для редактирования продавцов
  core_logistics_seller_admin:
    class: Core\LogisticsBundle\Admin\SellerAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, group: Бухгалтерия, label: "Продавцы" }
    arguments: [null, Core\LogisticsBundle\Entity\Seller, null]

  #сервис для редактирования RegionCity
  core_logistics_region_city_admin:
    class: Core\LogisticsBundle\Admin\RegionCityAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore, show_in_dashboard:false}
    arguments: [null, Core\LogisticsBundle\Entity\RegionCity, null]

  #сервис для редактирования поставщиков
  core_logistics_supplier_admin:
    class: Core\LogisticsBundle\Admin\SupplierAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, group: Бухгалтерия, label: "Поставщики"}
    arguments: [null, Core\LogisticsBundle\Entity\Supplier, null]

  #сервис для редактирования поставок
  core_logistics_supply_admin:
    class: Core\LogisticsBundle\Admin\SupplyAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, group: Бухгалтерия, label: "Поставки"}
    arguments: [null, Core\LogisticsBundle\Entity\Supply, null]

  #сервис для редактирования товарных позиций в поставке
  core_logistics_product_in_supply_admin:
    class: Core\LogisticsBundle\Admin\ProductInSupplyAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, show_in_dashboard:false}
    arguments: [null, Core\LogisticsBundle\Entity\ProductInSupply, null]

  #сервис для редактирования товарных единиц на складе
  core_logistics_unit_in_stock_admin:
    class: Core\LogisticsBundle\Admin\UnitInStockAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, group: Бухгалтерия, label: "Товар со всех складов"}
    arguments: [null, Core\LogisticsBundle\Entity\UnitInStock, CoreLogisticsBundle:Admin\UnitInStockAdmin]

  #сервис для редактирования транзитов
  core_logistics_transit_admin:
    class: Core\LogisticsBundle\Admin\TransitAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, group: Бухгалтерия, label: "Транзиты"}
    arguments: [null, Core\LogisticsBundle\Entity\Transit, null]

    #сервис для редактирования статусов транзитов
  core_logistics_transit_status_admin:
    class: Core\LogisticsBundle\Admin\TransitStatusAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, group: Бухгалтерия, label: "Статусы транзитов"}
    arguments: [null, Core\LogisticsBundle\Entity\TransitStatus, null]

    #сервис для редактирования статусов поставок
  core_logistics_supply_status_admin:
    class: Core\LogisticsBundle\Admin\SupplyStatusAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, group: Бухгалтерия, label: "Статусы поставок"}
    arguments: [null, Core\LogisticsBundle\Entity\SupplyStatus, null]

  #сервис для редактирования статусов единиц продуктов на складе
#  core_logistics_unit_status_admin:
#    class: Core\LogisticsBundle\Admin\UnitStatusAdmin
#    tags:
#    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, show_in_dashboard: false,  group: Бухгалтерия, label: "Статусы единиц товаров" }
#    arguments: [null, Core\LogisticsBundle\Entity\UnitStatus, null]

  #сервис для редактирования складов
  core_logistics_stock_admin:
    class: Core\LogisticsBundle\Admin\StockAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, group: Бухгалтерия, label: "Склады"}
    arguments: [null, Core\LogisticsBundle\Entity\Stock, null]

  #товары в транзите
  core_logistics_unit_in_transit_admin:
    class: Core\LogisticsBundle\Admin\ProductInTransitAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, show_in_dashboard: false, group: Бухгалтерия, label: "Товары в транзите"}
    arguments: [null, Core\LogisticsBundle\Entity\ProductInTransit, null]

  # подписчик событий для складов
  core_stock_subscriber:
    class: Core\LogisticsBundle\EventListener\StockSubscriber
    tags:
            - { name: doctrine.event_subscriber }
    arguments: ['@service_container']

    # подписчик событий для поставок
  core_supply_subscriber:
    class: Core\LogisticsBundle\EventListener\SupplySubscriber
    tags:
            - { name: doctrine.event_subscriber }
    arguments: ['@service_container']

    # подписчик событий для товарных единиц
  core_unit_in_stock_subscriber:
    class: Core\LogisticsBundle\EventListener\UnitInStockSubscriber
    tags:
            - { name: doctrine.event_subscriber }
    arguments: ['@service_container']

  # логика поставок
  core_supply_logic:
    class: Core\LogisticsBundle\Logic\SupplyLogic
    arguments: ['@doctrine.orm.entity_manager', '@core_logistics_logic']

  # общая логика логистики
  core_logistics_logic:
    class: Core\LogisticsBundle\Logic\LogisticsLogic
    arguments: ['@doctrine.orm.entity_manager']

  #тип формы для редактирования модификаций
  core_logistics_products_in_transit_type:
    class: Core\LogisticsBundle\Admin\Form\Type\ProductsInTransit
    tags:
        - { name: form.type, alias: products_in_transit }
  #тип формы для редактирования модификаций
  core_logistics_unit_in_stock_defect_type:
    class: Core\LogisticsBundle\Admin\Form\Type\UnitInStockDefectType
    tags:
        - { name: form.type, alias: unit_in_stock_defect }
    arguments: ['@doctrine.orm.entity_manager', '@service_container']

  #сервис для редактирования серийников для товарных позиций
  core_logistics_unit_serial_admin:
    class: Core\LogisticsBundle\Admin\UnitSerialsAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, show_in_dashboard: false }
    arguments: [null, Core\LogisticsBundle\Entity\UnitSerials, null]

    #сервис для редактирования причин списания товарной единицы
  core_logistics_unit_in_stock_defect_transit_admin:
    class: Core\LogisticsBundle\Admin\UnitInStockDefectReasonAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore,  group: Бухгалтерия, label: "Причины списания"}
    arguments: [null, Core\LogisticsBundle\Entity\UnitInStockDefectReason, null]


    #сервис для редактирования типов дополнительных расходов для поставок
  core_logistics_additional_costs_of_supply_type_admin:
    class: Core\LogisticsBundle\Admin\AdditionalCostsTypeOfSupplyAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore, show_in_dashboard: true, group: Бухгалтерия, label: "Типы расходов поставки"}
    arguments: [null, Core\LogisticsBundle\Entity\AdditionalCostsTypeOfSupply, null]
    
    
    #сервис для редактирования дополнительных расходов
  core_logistics_additional_costs_of_supply_admin:
    class: Core\LogisticsBundle\Admin\AdditionalCostsOfSupplyAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, show_in_dashboard: false, group: Бухгалтерия, label: "Расходы"}
    arguments: [null, Core\LogisticsBundle\Entity\AdditionalCostsOfSupply, null]    


   # форма загрузки прайсов для последущего анализа и обработки
  core_manufacturer_price_analysis_admin:
    class: Core\LogisticsBundle\Admin\SupplierPriceAnalysisAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore, group: "Статистика", label: "Анализ прайсов" }
    arguments: [null, Core\LogisticsBundle\Entity\SupplierPriceAnalysis, CoreLogisticsBundle:Admin\SupplierPriceAnalysisAdmin ]

  # логика для анализа загруженных прайсов
  core_logistics_supplier_price_analysis_logic:
    class:  Core\LogisticsBundle\Logic\SupplierPriceAnalysisLogic
    arguments: ['@doctrine.orm.entity_manager', '@phpexcel', '@core_file_logic']

  #админский клас для редактирования настроек анализа прайсов
  core_manufacturer_price_analysis_settings_admin:
    class: Core\LogisticsBundle\Admin\SupplierPriceAnalysisSettingsAdmin
    tags:
    - { name: sonata.admin,  manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore, show_in_dashboard: false }
    arguments: [null, Core\LogisticsBundle\Entity\SupplierPriceAnalysisSettings, null]

  # подписчик событий для прайсов от поставщиков
  core_supplier_price_analysis_subscriber:
     class: Core\LogisticsBundle\EventListener\SupplierPriceAnalysisSubscriber
     tags:
     - { name: doctrine.event_subscriber }
     arguments: ['@core_file_logic', '@phpexcel']
