# Вывод первой страницы списка сайтов в личном кабинете
core_cabinet_site_list_first_page:
    path:      /cabinet/sites.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SiteCabinet:list}

# Вывод списка сайтов в ЛК
core_cabinet_site_list:
    path:      /cabinet/sites/{page}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SiteCabinet:list, page: 1 }
    requirements:
      page: \d+

# редактирование сайта в ЛК
core_cabinet_site_edit:
    path:      /cabinet/site_edit_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SiteCabinet:edit }
    requirements:
      id: \d+


# добавление сайта в ЛК
core_cabinet_site_create:
    path:      /cabinet/site_create.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SiteCabinet:create }


# удаление сайта в ЛК
core_cabinet_site_delete:
    path:      /cabinet/site_delete_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SiteCabinet:delete }
    requirements:
      id: \d+

# форма подтверждения прав на площадку
core_cabinet_site_verified_form:
    path:      /cabinet/site_verified_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SiteCabinet:verifiedForm }
    requirements:
      id: \d+

# проверка прав на площадку
core_cabinet_site_verify:
    path:      /cabinet/site_verifу_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SiteCabinet:verifySite }
    requirements:
      id: \d+


# получение файла для подтверждения прав на площадку
core_cabinet_site_get_file_for_verify:
    path:      /cabinet/site_get_file_for_verify_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SiteCabinet:getFileForVerify }
    requirements:
      id: \d+





# Вывод первой страницы списка рекламных мест в личном кабинете
core_cabinet_adplace_list_first_page:
    path:      /cabinet/adplaces.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlaceCabinet:list}

# Вывод списка рекламных мест в ЛК
core_cabinet_adplace_list:
    path:      /cabinet/adplaces/{page}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlaceCabinet:list, page: 1 }
    requirements:
      page: \d+

# редактирование рекламных мест в ЛК
core_cabinet_adplace_edit:
    path:      /cabinet/adplace_edit_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlaceCabinet:edit }
    requirements:
      id: \d+


# добавление рекламного места в ЛК
core_cabinet_adplace_create:
    path:      /cabinet/adplace_create.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlaceCabinet:create }


# удаление рекламного места в ЛК
core_cabinet_adplace_delete:
    path:      /cabinet/adplace_delete_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlaceCabinet:delete }
    requirements:
      id: \d+

# получение HTML-кода для встраивания рекламного места в ЛК
core_cabinet_adplace_getcode:
    path:      /cabinet/adplace_getcode_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlaceCabinet:getCode }
    requirements:
      id: \d+





# Вывод первой страницы списка разделов для рекламных мест в личном кабинете
core_cabinet_section_list_first_page:
    path:      /cabinet/sections.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SectionCabinet:list}

# Вывод списка разделов для рекламных мест мест в ЛК
core_cabinet_section_list:
    path:      /cabinet/sections/{page}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SectionCabinet:list, page: 1 }
    requirements:
      page: \d+

# редактирование разделов для рекламных мест в ЛК
core_cabinet_section_edit:
    path:      /cabinet/section_edit_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SectionCabinet:edit }
    requirements:
      id: \d+


# добавление разделов для рекламных мест в ЛК
core_cabinet_section_create:
    path:      /cabinet/section_create.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SectionCabinet:create }

# добавление разделов для рекламных мест в ЛК (ajax)
core_cabinet_section_create_ajax:
    path:      /cabinet/section_create.json
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SectionCabinet:createAjax }

# редактирование разделов для рекламных мест в ЛК
core_cabinet_section_edit_ajax:
    path:      /cabinet/section_edit_{id}.json
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SectionCabinet:editAjax }
    requirements:
          id: \d+

# удаление разделов для рекламных мест в ЛК
core_cabinet_section_delete_ajax:
    path:      /cabinet/section_delete.json
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SectionCabinet:deleteAjax }

# удаление разделов для рекламных мест в ЛК
core_cabinet_section_delete:
    path:      /cabinet/section_delete_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SectionCabinet:delete }
    requirements:

# Вывод первой страницы списка рекламных мест в личном кабинете
core_cabinet_ad_place_price_first_page:
    path:      /cabinet/ad_place_price_list_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlacePrice:list }
    requirements:
          id: \d+

#Список цен для рекламных мест ЛК
core_cabinet_ad_place_price_list:
    path:      /cabinet/ad_place_price_list_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlacePrice:list }
    requirements:
          id: \d+

#добавление цены для рекламного места ЛК
core_cabinet_ad_place_price_create:
    path:      /cabinet/ad_place_price_create_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlacePrice:create }
    requirements:
          id: \d+

#изменение цены для рекламного места ЛК
core_cabinet_ad_place_price_edit:
    path:      /cabinet/ad_place_price_edit_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlacePrice:edit }
    requirements:
          id: \d+

#удаление цены для рекламного места ЛК
core_cabinet_ad_place_price_delete:
    path:      /cabinet/ad_place_price_delete_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlacePrice:delete }
    #methods:  ['POST']
    requirements:
          id: \d+

core_cabinet_adplace_section_edit:
    path:      /cabinet/ad_place_section_edit_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlaceCabinet:getAdplaceSections }
    requirements:
          id: \d+

core_create_site_img:
    path:      /cabinet/site/create-snap.json
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SiteCabinet:createSiteImage }
    requirements:
          id: \d+

core_site_details:
    path:      /site-{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:Site:show }
    requirements:
          id: \d+

core_common_catalog_first_page:
    path:      /sites-catalog.html
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:Site:siteCatalog}

core_common_catalog:
    pattern:  /sites-catalog/{page}.html
    schemes:  [http]
    defaults: { _controller: CoreCommonBundle:Site:siteCatalog }
    requirements:
      page: \d+




core_cabinet_ad_place_create_ajax:
    path:     /cabinet/place/create_ajax.json
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlaceCabinet:createAjax }

core_cabinet_ad_place_edit_ajax:
    path:     /cabinet/place/edit_ajax.json
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlaceCabinet:editAjax }

core_cabinet_site_create_ajax:
    path:     /cabinet/site/create_ajax.json
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SiteCabinet:createAjax }

core_cabinet_site_edit_ajax:
    path:     /cabinet/site/edit_ajax.json
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:SiteCabinet:editAjax }

core_cabinet_site_adplaces:
    path:      /site-adplaces.json
    schemes:  [http]
    defaults:  { _controller: CoreSiteBundle:AdPlaceCabinet:siteAdPlacesAjax }
