services:
  #админсике классы для площадок
  core_site_admin:
    class: Core\SiteBundle\Admin\SiteAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore,  group: Материалы, label: Площадки }
    arguments: [null, Core\SiteBundle\Entity\CommonSite, null]
    calls:
    - [ setSubClasses, [ { "Web-сайт": Core\SiteBundle\Entity\WebSite} ] ]


  #админсике классы для рекламных мест
  core_ad_place_admin:
    class: Core\SiteBundle\Admin\AdPlaceAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore,  group: Материалы, label: Рекламные места }
    arguments: [null, Core\SiteBundle\Entity\AdPlace, null]


  #админсике классы для разделов рекламных мест
  core_section_admin:
    class: Core\SiteBundle\Admin\SectionAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore,  group: Материалы, label: Разделы рекламных мест }
    arguments: [null, Core\SiteBundle\Entity\Section, null]


  # логика для сайтов
  core_site_logic:
    class: Core\SiteBundle\Logic\SiteLogic
    arguments: ['@router', '@doctrine.orm.entity_manager', '@service_container', '@application_knp_paginator_logic']


# логика для рекламных мест
  core_adplace_logic:
    class: Core\SiteBundle\Logic\AdPlaceLogic
    arguments: ['@router', '@doctrine.orm.entity_manager', '@service_container', '@application_knp_paginator_logic']


# логика для разделов рекламных мест
  core_section_logic:
    class: Core\SiteBundle\Logic\SectionLogic
    arguments: ['@router', '@doctrine.orm.entity_manager', '@service_container', '@application_knp_paginator_logic']

# подписчик для площадки
  core_site_subscriber:
    class: Core\SiteBundle\EventListener\SiteSubscriber
    tags:
        - { name: doctrine.event_subscriber }
    arguments: ['@service_container']
  core_section_form:
      class: Core\SiteBundle\Form\Type\SectionFormType
      tags:
          - { name: form.type, alias: section_form }

  core_section_form_type_extension:
      class: Core\SiteBundle\Form\Extension\EntityTypeExtension
      tags:
          - { name: form.type_extension, alias: entity }
