services:
  # логика для скидок
  core_discounts_logic:
    class: Core\DiscountsBundle\Logic\DiscountsLogic
    arguments: ['@doctrine.orm.entity_manager', '@service_container']
    
  #сервис для редактирования скидок для производителей
  core_discounts_manufacturer_admin:
    class: Core\DiscountsBundle\Admin\ManufacturerDiscountAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore,   group: Скидки, label: "Скидки по брендам" }
    arguments: [null, Core\DiscountsBundle\Entity\ManufacturerDiscount, null]

  #сервис для редактирования значений для скидок по производителям
  core_discounts_manufacturer_step_values_admin:
    class: Core\DiscountsBundle\Admin\ManufacturerStepValuesAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, show_in_dashboard: false,  group: Скидки, label: "Значения скидок по брендам" }
    arguments: [null, Core\DiscountsBundle\Entity\ManufacturerStepValues, null]

  #сервис для редактирования индивидуальных скидок для производителей
  core_discounts_contragent_manufacturer_admin:
    class: Core\DiscountsBundle\Admin\ContragentManufacturerDiscountAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore,   group: Скидки, label: "Индивидуальные cкидки по брендам" }
    arguments: [null, Core\DiscountsBundle\Entity\ContragentManufacturerDiscount, null]

  #сервис для редактирования значений для индивидуальных скидок по производителям
  core_discounts_contragent_manufacturer_step_values_admin:
    class: Core\DiscountsBundle\Admin\ContragentManufacturerStepValuesAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, show_in_dashboard: false,  group: Скидки, label: "Значения скидок по брендам" }
    arguments: [null, Core\DiscountsBundle\Entity\ContragentManufacturerStepValues, null]
#
#  #сервис для редактирования транспортных накладных
#  core_order_waybills_admin:
#    class: Core\OrderBundle\Admin\WaybillsAdmin
#    tags:
#    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore,  show_in_dashboard: false, group: Бухгалтерия, label: "Транспортные накладные" }
#    arguments: [null, Core\OrderBundle\Entity\Waybills, null]
#
#  #сервис для редактирования габаритов упаковок
#  core_order_sizes_of_box_admin:
#    class: Core\OrderBundle\Admin\SizesOfBoxAdmin
#    tags:
#    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore,  show_in_dashboard: false, group: Бухгалтерия, label: "Габариты упаковок" }
#    arguments: [null, Core\OrderBundle\Entity\SizesOfBox, null]
#
#  #сервис для редактирования продуктов в заказе
#  core_order_composition_admin:
#    class: Core\OrderBundle\Admin\CompositionAdmin
#    tags:
#    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore,  show_in_dashboard: false, group: Бухгалтерия, label: "Продукты в заказе" }
#    arguments: [null, Core\OrderBundle\Entity\Composition, null]
#

#
#  #тип формы для редактирования и отображения состава заказа
#  core_order_products_in_order_type:
#    class: Core\OrderBundle\Admin\Form\Type\ProductsInOrderType
#    arguments: ['@core_order_logic', '@doctrine.orm.entity_manager']
#    tags:
#        - { name: form.type, alias: products_in_order }

  # подписчик событий
#  core_order_subscriber:
#    class: Core\OrderBundle\EventListener\OrderSubscriber
#    tags:
#            - { name: doctrine.event_subscriber }
#    arguments: ['@service_container']