#добавляет товар в транзиты
core_order_add_to_transit:
    path:      /core_order_add_to_transit
    schemes:  [https]
    defaults:  { _controller: CoreOrderBundle:AdminAjaxOrder:addProductToTransit }

#обновляет серийники заказа
core_order_update_serials:
    path:      /core_order_update_serials
    schemes:  [https]
    defaults:  { _controller: CoreOrderBundle:AdminAjaxOrder:updateSerials }

#запрос на получение получателей у контрагента
core_order_get_contragent_receipments:
    path:      /core_order_get_contragent_receipments
    schemes:  [https]
    defaults:  { _controller: CoreOrderBundle:AdminAjaxOrder:getContragentReceipments }

#запрос на получение списка предзаказов для объединения
core_pre_order_get:
    path:      /core_pre_order_get
    schemes:  [https]
    defaults:  { _controller: CoreOrderBundle:AdminAjaxPreOrder:getPreOrders }

#запрос на объединение двух предзаказов
core_pre_order_combine:
    path:      /core_pre_order_combine
    schemes:  [https]
    defaults:  { _controller: CoreOrderBundle:AdminAjaxPreOrder:combinePreOrders }

#запрос на объединение двух предзаказов
core_order_create_new_supply:
    path:      /create_new_supply
    schemes:  [https]
    defaults:  { _controller: CoreOrderBundle:AdminAjaxOrder:createNewSupply }

