services:
  #сервис для редактирования заказов
  core_order_admin:
    class: Core\OrderBundle\Admin\OrderAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore,   group: Бухгалтерия, label: "Заказы" }
    arguments: [null, Core\OrderBundle\Entity\Order, "CoreOrderBundle:Admin\OrderAdmin"]

  #сервис для редактирования транспортных накладных
  core_order_waybills_admin:
    class: Core\OrderBundle\Admin\WaybillsAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore,  show_in_dashboard: false, group: Бухгалтерия, label: "Транспортные накладные" }
    arguments: [null, Core\OrderBundle\Entity\Waybills, null]

  #сервис для редактирования габаритов упаковок
  core_order_sizes_of_box_admin:
    class: Core\OrderBundle\Admin\SizesOfBoxAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore,  show_in_dashboard: false, group: Бухгалтерия, label: "Габариты упаковок" }
    arguments: [null, Core\OrderBundle\Entity\SizesOfBox, null]

  #сервис для редактирования продуктов в заказе
  core_order_composition_admin:
    class: Core\OrderBundle\Admin\CompositionAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore,  show_in_dashboard: false, group: Бухгалтерия, label: "Продукты в заказе" }
    arguments: [null, Core\OrderBundle\Entity\Composition, null]


    #сервис для редактирования дополнительных статусов заказа
  core_order_extra_status_admin:
    class: Core\OrderBundle\Admin\ExtraStatusAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore,  show_in_dashboard: true, group: Бухгалтерия, label: "Доп. статусы заказов" }
    arguments: [null, Core\OrderBundle\Entity\ExtraStatus, null, '@security.context']


    #сервис для редактирования причин отмены закза
  core_order_canceled_reason_admin:
    class: Core\OrderBundle\Admin\CanceledReasonAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore, label: Причины отмены заказов }
    arguments: [null, Core\OrderBundle\Entity\CanceledReason, null]

  # логика для заказов
  core_order_logic:
    class: Core\OrderBundle\Logic\OrderLogic
    arguments: ['@doctrine.orm.entity_manager', '@core_logistics_logic', '@core_discounts_logic', '@tfox.mpdfport','@templating', '@session', '@service_container', '@mailer', '@security.context', {'default_currency':%default_currency%}, '@validator', '@router']

  #тип формы для редактирования и отображения состава заказа
  core_order_products_in_order_type:
    class: Core\OrderBundle\Admin\Form\Type\ProductsInOrderType
    arguments: ['@core_order_logic', '@doctrine.orm.entity_manager']
    tags:
        - { name: form.type, alias: products_in_order }


  #тип формы для редактирования и отображения состава заказа
  core_order_unit_serial_number_type:
    class: Core\OrderBundle\Admin\Form\Type\UnitSerialNumberType
    arguments: ['@core_order_logic', '@doctrine.orm.entity_manager']
    tags:
        - { name: form.type, alias: unit_serial_number }

  #подписчик событий
  core_order_subscriber:
    class: Core\OrderBundle\EventListener\OrderSubscriber
    tags:
            - { name: doctrine.event_subscriber }
    arguments: ['@service_container']


  #тип формы для редактирования и отображения траспортных накладных и упаковок
  core_order_boxes_and_waybills_type:
    class: Core\OrderBundle\Admin\Form\Type\BoxesAndWaybillsType
    tags:
        - { name: form.type, alias: boxes_and_waybills_type }

  #тип формы для редактирования и отображения траспортных накладных и упаковок
  core_order_waybills_type:
    class: Core\OrderBundle\Admin\Form\Type\WaybillsType
    tags:
        - { name: form.type, alias: waybills_in_order }

  #тип формы для редактирования и отображения траспортных накладных и упаковок
  core_order_boxes_type:
    class: Core\OrderBundle\Admin\Form\Type\BoxType
    tags:
        - { name: form.type, alias: boxes_in_order }

    #тип формы для редактирования и отображения статуса отмены в заказе
  core_order_canceled_reason_type:
    class: Core\OrderBundle\Admin\Form\Type\CanceledStatusType
    tags:
        - { name: form.type, alias: canceled_status }
    arguments: ['@core_order_logic', '@doctrine.orm.entity_manager', '@service_container']

    #тип формы для редактирования и отображения дополнительных статусов в заказе
  core_order_extra_status_type:
    class: Core\OrderBundle\Admin\Form\Type\ExtraStatusType
    tags:
        - { name: form.type, alias: extra_status }
    arguments: ['@doctrine.orm.entity_manager']

  #дополнительный валидатор для заказа
  core_order_order_extra_validator:
      class: Core\OrderBundle\Validator\Constraints\OrderExtraValidator
      arguments: ['@core_order_logic', '@validator', '@service_container', '@router']
      tags:
            - { name: validator.constraint_validator, alias: core_order_order_extra }


  core_order_check_composition_validator:
      class: Core\OrderBundle\Validator\Constraints\CheckCompositionValidator
      arguments: ['@doctrine.orm.entity_manager']
      tags:
            - { name: validator.constraint_validator, alias: core_order_check_composition }
            
  #Форма покупатель - получатель корзина
  core_order_buyer_recipient_info_form:
      class: Core\OrderBundle\Form\Type\BuyerInfoFormType
      arguments: ['@security.context', '@request_stack', '@fos_user.user_manager', '@doctrine.orm.entity_manager', '@validator', '@session']
      tags:
          - { name: form.type, alias: cart_buyer_recipient }
          
  #Форма получатель cо списком получателей и доп полями
  core_order_recipient_with_extra_data_form:
      class: Core\OrderBundle\Form\Type\RecipientFormType
      arguments: ['@security.context']
      tags:
          - { name: form.type, alias: cart_recipient_with_extra_data }        

    # логика для заказо, для отправки различных писем
  core_order_mailer_logic:
    class: Core\OrderBundle\Logic\OrderMailerLogic
    arguments: ['@mailer', '@router', '@templating', '@translator', '@core_config_logic', '@core_common_twig_extension', '@twig', {'default_email_sender_name': %default_email_sender_name%, 'default_email': %default_email% , 'default_timezone': %default_timezone%}, '@core_order_logic']
        
  # Логика для предзаказа
  core_pre_order_logic:
    class: Core\OrderBundle\Logic\PreOrderLogic
    arguments: ['@doctrine.orm.entity_manager', '@fos_user.user_manager', '@validator', '@core_order_logic', '@core_supply_logic', '@translator', '@session', '@core_common_money_twig_extension', '@security.context',  '@templating', '@router', {'default_email': %default_email%, 'default_email': %default_email%}, '@mailer', '@form.factory']
                 
  #Форма предзаказ со списком получателей
  core_pre_order_form:
      class: Core\OrderBundle\Form\Type\PreOrderFormType
      tags:
          - { name: form.type, alias: pre_order_form }
  
  #Форма состава предзаказа
  core_pre_order_composition_form:
      class: Core\OrderBundle\Form\Type\PreOrderCompostionFormType
      tags:
          - { name: form.type, alias: pre_order_composition_form }
          
  #Статусы предзаказов
  core_pre_order_status_admin:
    class: Core\OrderBundle\Admin\PreOrderStatusAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore,  group: Бухгалтерия, label: Статусы Предзаказов }
    arguments: [null, Core\OrderBundle\Entity\PreOrder\PreOrderStatus, null]

  #Состав предзаказа в админке
  core_pre_order_compositions_admin:
    class: Core\OrderBundle\Admin\PreOrderCompositionAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore, show_in_dashboard: false }
    arguments: [null, Core\OrderBundle\Entity\PreOrder\PreOrderComposition, null]

  #админсике классы для предзаказов
  core_pre_order_admin:
    class: Core\OrderBundle\Admin\PreOrderAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: true, label_translator_strategy: sonata.admin.label.strategy.underscore,  group: Бухгалтерия, label: Предзаказы }
    arguments: [null, Core\OrderBundle\Entity\PreOrder\PreOrder, CoreOrderBundle:Admin\PreOrderAdmin]