<?php

namespace Proxies\__CG__\Core\LogisticsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Supplier extends \Core\LogisticsBundle\Entity\Supplier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'legalForm', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'caption', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'inn', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'kpp', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'ogrn', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'positionOfTheHead', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'nameOfTheHead', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'country', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'city', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'addressUr', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'addressPost', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'phone', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'fax', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'bic', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'paymentAccount', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'site', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'email', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'paSettings', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'paCurrency', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'minSumForOrder');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'legalForm', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'caption', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'inn', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'kpp', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'ogrn', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'positionOfTheHead', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'nameOfTheHead', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'country', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'city', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'addressUr', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'addressPost', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'phone', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'fax', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'bic', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'paymentAccount', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'site', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'email', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'paSettings', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'paCurrency', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Supplier' . "\0" . 'minSumForOrder');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Supplier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLegalForm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLegalForm', array());

        return parent::getLegalForm();
    }

    /**
     * {@inheritDoc}
     */
    public function setLegalForm($legalForm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLegalForm', array($legalForm));

        return parent::setLegalForm($legalForm);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaption', array());

        return parent::getCaption();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaption($caption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaption', array($caption));

        return parent::setCaption($caption);
    }

    /**
     * {@inheritDoc}
     */
    public function getInn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInn', array());

        return parent::getInn();
    }

    /**
     * {@inheritDoc}
     */
    public function setInn($inn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInn', array($inn));

        return parent::setInn($inn);
    }

    /**
     * {@inheritDoc}
     */
    public function getKpp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKpp', array());

        return parent::getKpp();
    }

    /**
     * {@inheritDoc}
     */
    public function setKpp($kpp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKpp', array($kpp));

        return parent::setKpp($kpp);
    }

    /**
     * {@inheritDoc}
     */
    public function getOgrn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOgrn', array());

        return parent::getOgrn();
    }

    /**
     * {@inheritDoc}
     */
    public function setOgrn($ogrn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOgrn', array($ogrn));

        return parent::setOgrn($ogrn);
    }

    /**
     * {@inheritDoc}
     */
    public function getPositionOfTheHead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPositionOfTheHead', array());

        return parent::getPositionOfTheHead();
    }

    /**
     * {@inheritDoc}
     */
    public function setPositionOfTheHead($positionOfTheHead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPositionOfTheHead', array($positionOfTheHead));

        return parent::setPositionOfTheHead($positionOfTheHead);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameOfTheHead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameOfTheHead', array());

        return parent::getNameOfTheHead();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameOfTheHead($nameOfTheHead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameOfTheHead', array($nameOfTheHead));

        return parent::setNameOfTheHead($nameOfTheHead);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressUr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressUr', array());

        return parent::getAddressUr();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressUr($addressUr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressUr', array($addressUr));

        return parent::setAddressUr($addressUr);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressPost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressPost', array());

        return parent::getAddressPost();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressPost($addressPost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressPost', array($addressPost));

        return parent::setAddressPost($addressPost);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getBic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBic', array());

        return parent::getBic();
    }

    /**
     * {@inheritDoc}
     */
    public function setBic($bic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBic', array($bic));

        return parent::setBic($bic);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAccount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAccount', array());

        return parent::getPaymentAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentAccount($paymentAccount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentAccount', array($paymentAccount));

        return parent::setPaymentAccount($paymentAccount);
    }

    /**
     * {@inheritDoc}
     */
    public function getSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSite', array());

        return parent::getSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSite($site)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSite', array($site));

        return parent::setSite($site);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaSettings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaSettings', array());

        return parent::getPaSettings();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaSettings($paSettings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaSettings', array($paSettings));

        return parent::setPaSettings($paSettings);
    }

    /**
     * {@inheritDoc}
     */
    public function addPaSetting($paSetting)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPaSetting', array($paSetting));

        return parent::addPaSetting($paSetting);
    }

    /**
     * {@inheritDoc}
     */
    public function removePaSetting($paSetting)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePaSetting', array($paSetting));

        return parent::removePaSetting($paSetting);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaCurrency', array());

        return parent::getPaCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaCurrency($paCurrency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaCurrency', array($paCurrency));

        return parent::setPaCurrency($paCurrency);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinSumForOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinSumForOrder', array());

        return parent::getMinSumForOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinSumForOrder($minSumForOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinSumForOrder', array($minSumForOrder));

        return parent::setMinSumForOrder($minSumForOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function isValid(\Symfony\Component\Validator\ExecutionContextInterface $context)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValid', array($context));

        return parent::isValid($context);
    }

}
