<?php

namespace Proxies\__CG__\Core\LogisticsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bank extends \Core\LogisticsBundle\Entity\Bank implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'caption', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'captionFull', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'license', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'isLicenseCanceled', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'bic', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'swift', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'correspondentAccount', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'okpo', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'parentBank', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'city', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'address', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'phones', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'site', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'email', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'idIn1c');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'caption', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'captionFull', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'license', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'isLicenseCanceled', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'bic', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'swift', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'correspondentAccount', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'okpo', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'parentBank', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'city', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'address', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'phones', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'site', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'email', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Bank' . "\0" . 'idIn1c');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bank $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCaption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaption', array());

        return parent::getCaption();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaption($caption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaption', array($caption));

        return parent::setCaption($caption);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaptionFull()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaptionFull', array());

        return parent::getCaptionFull();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaptionFull($captionFull)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaptionFull', array($captionFull));

        return parent::setCaptionFull($captionFull);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicense()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicense', array());

        return parent::getLicense();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicense($license)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicense', array($license));

        return parent::setLicense($license);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsLicenseCanceled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsLicenseCanceled', array());

        return parent::getIsLicenseCanceled();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsLicenseCanceled($isLicenseCanceled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsLicenseCanceled', array($isLicenseCanceled));

        return parent::setIsLicenseCanceled($isLicenseCanceled);
    }

    /**
     * {@inheritDoc}
     */
    public function getBic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBic', array());

        return parent::getBic();
    }

    /**
     * {@inheritDoc}
     */
    public function setBic($bic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBic', array($bic));

        return parent::setBic($bic);
    }

    /**
     * {@inheritDoc}
     */
    public function getSwift()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSwift', array());

        return parent::getSwift();
    }

    /**
     * {@inheritDoc}
     */
    public function setSwift($swift)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSwift', array($swift));

        return parent::setSwift($swift);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorrespondentAccount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorrespondentAccount', array());

        return parent::getCorrespondentAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorrespondentAccount($correspondentAccount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorrespondentAccount', array($correspondentAccount));

        return parent::setCorrespondentAccount($correspondentAccount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOkpo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOkpo', array());

        return parent::getOkpo();
    }

    /**
     * {@inheritDoc}
     */
    public function setOkpo($okpo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOkpo', array($okpo));

        return parent::setOkpo($okpo);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentBank()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentBank', array());

        return parent::getParentBank();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentBank($parentBank)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentBank', array($parentBank));

        return parent::setParentBank($parentBank);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhones', array());

        return parent::getPhones();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhones($phones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhones', array($phones));

        return parent::setPhones($phones);
    }

    /**
     * {@inheritDoc}
     */
    public function getSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSite', array());

        return parent::getSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSite($site)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSite', array($site));

        return parent::setSite($site);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdIn1c()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdIn1c', array());

        return parent::getIdIn1c();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdIn1c($idIn1c)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdIn1c', array($idIn1c));

        return parent::setIdIn1c($idIn1c);
    }

}
