<?php

namespace Core\DirectoryBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CurrencyAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\DirectoryBundle\Controller\Admin\CurrencyAdminController();
        return $instance;
    }
}
