<?php

namespace Core\FaqBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FaqController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\FaqBundle\Controller\FaqController();
        return $instance;
    }
}
