<?php

namespace Gregwar\CaptchaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CaptchaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Gregwar\CaptchaBundle\Controller\CaptchaController();
        return $instance;
    }
}
