<?php

namespace Proxies\__CG__\Core\ProductBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \Core\ProductBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'reviews', 'reviewsRating', 'reviewsCount', 'remoteVideos', 'virtualCategoryList', 'captionRu', 'captionEn', 'shortDescriptionRu', 'shortDescriptionEn', 'descriptionRu', 'descriptionEn', 'complectationRu', 'complectationEn', 'sloganRu', 'sloganEn', 'titleRu', 'titleEn', 'metakeywordsRu', 'metakeywordsEn', 'metadescriptionRu', 'metadescriptionEn', 'captionCaseRu', 'captionCaseEn');
        }

        return array('__isInitialized__', 'id', 'reviews', 'reviewsRating', 'reviewsCount', 'remoteVideos', 'virtualCategoryList', 'captionRu', 'captionEn', 'shortDescriptionRu', 'shortDescriptionEn', 'descriptionRu', 'descriptionEn', 'complectationRu', 'complectationEn', 'sloganRu', 'sloganEn', 'titleRu', 'titleEn', 'metakeywordsRu', 'metakeywordsEn', 'metadescriptionRu', 'metadescriptionEn', 'captionCaseRu', 'captionCaseEn');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getReviews()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviews', array());

        return parent::getReviews();
    }

    /**
     * {@inheritDoc}
     */
    public function setReviews($reviews)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReviews', array($reviews));

        return parent::setReviews($reviews);
    }

    /**
     * {@inheritDoc}
     */
    public function getReviewsRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviewsRating', array());

        return parent::getReviewsRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setReviewsRating($reviewsRating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReviewsRating', array($reviewsRating));

        return parent::setReviewsRating($reviewsRating);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryMain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryMain', array());

        return parent::getCategoryMain();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryMain($categoryMain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryMain', array($categoryMain));

        return parent::setCategoryMain($categoryMain);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', array());

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategories($categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategories', array($categories));

        return parent::setCategories($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexPosition', array());

        return parent::getIndexPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndexPosition($indexPosition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndexPosition', array($indexPosition));

        return parent::setIndexPosition($indexPosition);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexPositionModification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexPositionModification', array());

        return parent::getIndexPositionModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndexPositionModification($indexPositionModification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndexPositionModification', array($indexPositionModification));

        return parent::setIndexPositionModification($indexPositionModification);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDateTime', array());

        return parent::getCreatedDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDateTime($createdDateTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDateTime', array($createdDateTime));

        return parent::setCreatedDateTime($createdDateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsEnabled', array());

        return parent::getIsEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsEnabled($isEnabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsEnabled', array($isEnabled));

        return parent::setIsEnabled($isEnabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsBest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsBest', array());

        return parent::getIsBest();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsBest($isBest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsBest', array($isBest));

        return parent::setIsBest($isBest);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDiscontinued()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDiscontinued', array());

        return parent::getIsDiscontinued();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDiscontinued($isDiscontinued)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDiscontinued', array($isDiscontinued));

        return parent::setIsDiscontinued($isDiscontinued);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticle', array());

        return parent::getArticle();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticle($article)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticle', array($article));

        return parent::setArticle($article);
    }

    /**
     * {@inheritDoc}
     */
    public function setSku($sku)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSku', array($sku));

        return parent::setSku($sku);
    }

    /**
     * {@inheritDoc}
     */
    public function getSku()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSku', array());

        return parent::getSku();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getBarcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBarcode', array());

        return parent::getBarcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setBarcode($barcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBarcode', array($barcode));

        return parent::setBarcode($barcode);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getOldPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldPrice', array());

        return parent::getOldPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldPrice($oldPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldPrice', array($oldPrice));

        return parent::setOldPrice($oldPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturers', array());

        return parent::getManufacturers();
    }

    /**
     * {@inheritDoc}
     */
    public function setManufacturers($manufacturers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManufacturers', array($manufacturers));

        return parent::setManufacturers($manufacturers);
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturerMain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturerMain', array());

        return parent::getManufacturerMain();
    }

    /**
     * {@inheritDoc}
     */
    public function setManufacturerMain($manufacturerMain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManufacturerMain', array($manufacturerMain));

        return parent::setManufacturerMain($manufacturerMain);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', array());

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand($brand)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', array($brand));

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductDataProperty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductDataProperty', array());

        return parent::getProductDataProperty();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductDataProperty(\Doctrine\Common\Collections\ArrayCollection $productDataProperty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductDataProperty', array($productDataProperty));

        return parent::setProductDataProperty($productDataProperty);
    }

    /**
     * {@inheritDoc}
     */
    public function addProductDataProperty(\Core\PropertyBundle\Entity\ProductDataProperty $productDataProperty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductDataProperty', array($productDataProperty));

        return parent::addProductDataProperty($productDataProperty);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductDataProperty(\Core\PropertyBundle\Entity\ProductDataProperty $productDataProperty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductDataProperty', array($productDataProperty));

        return parent::removeProductDataProperty($productDataProperty);
    }

    /**
     * {@inheritDoc}
     */
    public function getPDPByPropertyName($property_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPDPByPropertyName', array($property_name));

        return parent::getPDPByPropertyName($property_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getModificationUnion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModificationUnion', array());

        return parent::getModificationUnion();
    }

    /**
     * {@inheritDoc}
     */
    public function setModificationUnion($modificationUnion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModificationUnion', array($modificationUnion));

        return parent::setModificationUnion($modificationUnion);
    }

    /**
     * {@inheritDoc}
     */
    public function getSimilars()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSimilars', array());

        return parent::getSimilars();
    }

    /**
     * {@inheritDoc}
     */
    public function setSimilars($similars)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSimilars', array($similars));

        return parent::setSimilars($similars);
    }

    /**
     * {@inheritDoc}
     */
    public function addSimilars($similars)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSimilars', array($similars));

        return parent::addSimilars($similars);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSimilars($similars)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSimilars', array($similars));

        return parent::removeSimilars($similars);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessories', array());

        return parent::getAccessories();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccessories($accessories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccessories', array($accessories));

        return parent::setAccessories($accessories);
    }

    /**
     * {@inheritDoc}
     */
    public function addAccessories($accessories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAccessories', array($accessories));

        return parent::addAccessories($accessories);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAccessories($accessories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAccessories', array($accessories));

        return parent::removeAccessories($accessories);
    }

    /**
     * {@inheritDoc}
     */
    public function getServices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServices', array());

        return parent::getServices();
    }

    /**
     * {@inheritDoc}
     */
    public function setServices($services)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServices', array($services));

        return parent::setServices($services);
    }

    /**
     * {@inheritDoc}
     */
    public function addServices($services)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addServices', array($services));

        return parent::addServices($services);
    }

    /**
     * {@inheritDoc}
     */
    public function removeServices($services)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeServices', array($services));

        return parent::removeServices($services);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlternative()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlternative', array());

        return parent::getAlternative();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlternative($alternative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlternative', array($alternative));

        return parent::setAlternative($alternative);
    }

    /**
     * {@inheritDoc}
     */
    public function addAlternative($alternative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAlternative', array($alternative));

        return parent::addAlternative($alternative);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAlternative($alternative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAlternative', array($alternative));

        return parent::removeAlternative($alternative);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageMain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageMain', array());

        return parent::getImageMain();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageMain($imageMain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageMain', array($imageMain));

        return parent::setImageMain($imageMain);
    }

    /**
     * {@inheritDoc}
     */
    public function addImageMain($imageMain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImageMain', array($imageMain));

        return parent::addImageMain($imageMain);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImageMain($imageMain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImageMain', array($imageMain));

        return parent::removeImageMain($imageMain);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', array());

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function setImages($images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImages', array($images));

        return parent::setImages($images);
    }

    /**
     * {@inheritDoc}
     */
    public function addImages($images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImages', array($images));

        return parent::addImages($images);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImages($images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImages', array($images));

        return parent::removeImages($images);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', array());

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setColor($color)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', array($color));

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getColorOriginalCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColorOriginalCode', array());

        return parent::getColorOriginalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setColorOriginalCode($colorOriginalCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColorOriginalCode', array($colorOriginalCode));

        return parent::setColorOriginalCode($colorOriginalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsColorSelectedByUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsColorSelectedByUser', array());

        return parent::getIsColorSelectedByUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsColorSelectedByUser($isColorSelectedByUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsColorSelectedByUser', array($isColorSelectedByUser));

        return parent::setIsColorSelectedByUser($isColorSelectedByUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstruction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstruction', array());

        return parent::getInstruction();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstruction($instruction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstruction', array($instruction));

        return parent::setInstruction($instruction);
    }

    /**
     * {@inheritDoc}
     */
    public function addInstruction($instruction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInstruction', array($instruction));

        return parent::addInstruction($instruction);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInstruction($instruction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInstruction', array($instruction));

        return parent::removeInstruction($instruction);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductAvailability()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductAvailability', array());

        return parent::getProductAvailability();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductAvailability($productAvailability)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductAvailability', array($productAvailability));

        return parent::setProductAvailability($productAvailability);
    }

    /**
     * {@inheritDoc}
     */
    public function addProductAvailability($productAvailability)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductAvailability', array($productAvailability));

        return parent::addProductAvailability($productAvailability);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductAvailability($productAvailability)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductAvailability', array($productAvailability));

        return parent::removeProductAvailability($productAvailability);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailabilityQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailabilityQuantity', array());

        return parent::getAvailabilityQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailabilityQuantityReal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailabilityQuantityReal', array());

        return parent::getAvailabilityQuantityReal();
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailabilityQuantityVirtualReal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailabilityQuantityVirtualReal', array());

        return parent::getAvailabilityQuantityVirtualReal();
    }

    /**
     * {@inheritDoc}
     */
    public function getArticleAndCaption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticleAndCaption', array());

        return parent::getArticleAndCaption();
    }

    /**
     * {@inheritDoc}
     */
    public function getSerialsQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerialsQuantity', array());

        return parent::getSerialsQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerialsQuantity($serialsQuantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerialsQuantity', array($serialsQuantity));

        return parent::setSerialsQuantity($serialsQuantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnits', array());

        return parent::getUnits();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnits($units)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnits', array($units));

        return parent::setUnits($units);
    }

    /**
     * {@inheritDoc}
     */
    public function getFavoriteUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFavoriteUsers', array());

        return parent::getFavoriteUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function setFavoriteUsers($favoriteUsers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFavoriteUsers', array($favoriteUsers));

        return parent::setFavoriteUsers($favoriteUsers);
    }

    /**
     * {@inheritDoc}
     */
    public function addFavoriteUsers($favoriteUsers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFavoriteUsers', array($favoriteUsers));

        return parent::addFavoriteUsers($favoriteUsers);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFavoriteUsers($favoriteUsers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFavoriteUsers', array($favoriteUsers));

        return parent::removeFavoriteUsers($favoriteUsers);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoryUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoryUsers', array());

        return parent::getHistoryUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoryUsers($historyUsers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoryUsers', array($historyUsers));

        return parent::setHistoryUsers($historyUsers);
    }

    /**
     * {@inheritDoc}
     */
    public function addHistoryUsers($historyUsers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHistoryUsers', array($historyUsers));

        return parent::addHistoryUsers($historyUsers);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHistoryUsers($historyUsers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHistoryUsers', array($historyUsers));

        return parent::removeHistoryUsers($historyUsers);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsNoSerials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsNoSerials', array());

        return parent::getIsNoSerials();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsNoSerials($isNoSerials)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsNoSerials', array($isNoSerials));

        return parent::setIsNoSerials($isNoSerials);
    }

    /**
     * {@inheritDoc}
     */
    public function getWarrantyMonths()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWarrantyMonths', array());

        return parent::getWarrantyMonths();
    }

    /**
     * {@inheritDoc}
     */
    public function setWarrantyMonths($warrantyMonths)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWarrantyMonths', array($warrantyMonths));

        return parent::setWarrantyMonths($warrantyMonths);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantityAlternative()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantityAlternative', array());

        return parent::getQuantityAlternative();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantityAlternative($quantityAlternative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantityAlternative', array($quantityAlternative));

        return parent::setQuantityAlternative($quantityAlternative);
    }

    /**
     * {@inheritDoc}
     */
    public function addQuantityAlternative($quantityAlternative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addQuantityAlternative', array($quantityAlternative));

        return parent::addQuantityAlternative($quantityAlternative);
    }

    /**
     * {@inheritDoc}
     */
    public function removeQuantityAlternative($quantityAlternative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeQuantityAlternative', array($quantityAlternative));

        return parent::removeQuantityAlternative($quantityAlternative);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantityOfPieces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantityOfPieces', array());

        return parent::getQuantityOfPieces();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantityOfPieces($quantityOfPieces)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantityOfPieces', array($quantityOfPieces));

        return parent::setQuantityOfPieces($quantityOfPieces);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnitOfMeasure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnitOfMeasure', array());

        return parent::getUnitOfMeasure();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnitOfMeasure($unitOfMeasure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnitOfMeasure', array($unitOfMeasure));

        return parent::setUnitOfMeasure($unitOfMeasure);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerie', array());

        return parent::getSerie();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerie($serie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerie', array($serie));

        return parent::setSerie($serie);
    }

    /**
     * {@inheritDoc}
     */
    public function addReview($review)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReview', array($review));

        return parent::addReview($review);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReview($review)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReview', array($review));

        return parent::removeReview($review);
    }

    /**
     * {@inheritDoc}
     */
    public function getReviewsCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviewsCount', array());

        return parent::getReviewsCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setReviewsCount($reviewsCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReviewsCount', array($reviewsCount));

        return parent::setReviewsCount($reviewsCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemoteVideos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemoteVideos', array());

        return parent::getRemoteVideos();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemoteVideos($remoteVideos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemoteVideos', array($remoteVideos));

        return parent::setRemoteVideos($remoteVideos);
    }

    /**
     * {@inheritDoc}
     */
    public function addRemoteVideo($remoteVideo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRemoteVideo', array($remoteVideo));

        return parent::addRemoteVideo($remoteVideo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRemoteVideo(\Core\DirectoryBundle\Entity\RemoteVideo $remoteVideo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRemoteVideo', array($remoteVideo));

        return parent::removeRemoteVideo($remoteVideo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryOfOrigin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryOfOrigin', array());

        return parent::getCountryOfOrigin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountryOfOrigin($countryOfOrigin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountryOfOrigin', array($countryOfOrigin));

        return parent::setCountryOfOrigin($countryOfOrigin);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypePrefix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypePrefix', array());

        return parent::getTypePrefix();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypePrefix($typePrefix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypePrefix', array($typePrefix));

        return parent::setTypePrefix($typePrefix);
    }

    /**
     * {@inheritDoc}
     */
    public function getInOrderCompositions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInOrderCompositions', array());

        return parent::getInOrderCompositions();
    }

    /**
     * {@inheritDoc}
     */
    public function setInOrderCompositions($inOrderCompositions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInOrderCompositions', array($inOrderCompositions));

        return parent::setInOrderCompositions($inOrderCompositions);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsVisible', array());

        return parent::getIsVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsVisible($isVisible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsVisible', array($isVisible));

        return parent::setIsVisible($isVisible);
    }

    /**
     * {@inheritDoc}
     */
    public function getVirtualCategoryList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVirtualCategoryList', array());

        return parent::getVirtualCategoryList();
    }

    /**
     * {@inheritDoc}
     */
    public function setVirtualCategoryList($virtualCategoryList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVirtualCategoryList', array($virtualCategoryList));

        return parent::setVirtualCategoryList($virtualCategoryList);
    }

    /**
     * {@inheritDoc}
     */
    public function addVirtualCategoryList($virtualCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVirtualCategoryList', array($virtualCategory));

        return parent::addVirtualCategoryList($virtualCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVirtualCategoryList(\Core\CategoryBundle\Entity\ProductVirtualCategory $virtualCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVirtualCategoryList', array($virtualCategory));

        return parent::removeVirtualCategoryList($virtualCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getTickets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTickets', array());

        return parent::getTickets();
    }

    /**
     * {@inheritDoc}
     */
    public function setTickets($tickets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTickets', array($tickets));

        return parent::setTickets($tickets);
    }

    /**
     * {@inheritDoc}
     */
    public function addTicket($ticket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTicket', array($ticket));

        return parent::addTicket($ticket);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTicket($ticket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTicket', array($ticket));

        return parent::removeTicket($ticket);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderOnly()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderOnly', array());

        return parent::getOrderOnly();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderOnlyPriceBuying()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderOnlyPriceBuying', array());

        return parent::getOrderOnlyPriceBuying();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderOnlyShopTax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderOnlyShopTax', array());

        return parent::getOrderOnlyShopTax();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderOnlyShopTaxInPercent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderOnlyShopTaxInPercent', array());

        return parent::getOrderOnlyShopTaxInPercent();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryDays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryDays', array());

        return parent::getDeliveryDays();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryDays($deliveryDays)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryDays', array($deliveryDays));

        return parent::setDeliveryDays($deliveryDays);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderOnly($orderOnly)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderOnly', array($orderOnly));

        return parent::setOrderOnly($orderOnly);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderOnlyPriceBuying($orderOnlyPriceBuying)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderOnlyPriceBuying', array($orderOnlyPriceBuying));

        return parent::setOrderOnlyPriceBuying($orderOnlyPriceBuying);
    }

    /**
     * {@inheritDoc}
     */
    public function getOOPBCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOOPBCurrency', array());

        return parent::getOOPBCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setOOPBCurrency($OOPBCurrency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOOPBCurrency', array($OOPBCurrency));

        return parent::setOOPBCurrency($OOPBCurrency);
    }

    /**
     * {@inheritDoc}
     */
    public function getOOPBCurrencyRateAdditive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOOPBCurrencyRateAdditive', array());

        return parent::getOOPBCurrencyRateAdditive();
    }

    /**
     * {@inheritDoc}
     */
    public function setOOPBCurrencyRateAdditive($OOPBCurrencyRateAdditive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOOPBCurrencyRateAdditive', array($OOPBCurrencyRateAdditive));

        return parent::setOOPBCurrencyRateAdditive($OOPBCurrencyRateAdditive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsMrcEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsMrcEnabled', array());

        return parent::getIsMrcEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsMrcEnabled($isMrcEnabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsMrcEnabled', array($isMrcEnabled));

        return parent::setIsMrcEnabled($isMrcEnabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getMrc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMrc', array());

        return parent::getMrc();
    }

    /**
     * {@inheritDoc}
     */
    public function setMrc($mrc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMrc', array($mrc));

        return parent::setMrc($mrc);
    }

    /**
     * {@inheritDoc}
     */
    public function getOOPBQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOOPBQuantity', array());

        return parent::getOOPBQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setOOPBQuantity($OOPBQuantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOOPBQuantity', array($OOPBQuantity));

        return parent::setOOPBQuantity($OOPBQuantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsOOPBCurrencyRateAdditiveInPercent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsOOPBCurrencyRateAdditiveInPercent', array());

        return parent::getIsOOPBCurrencyRateAdditiveInPercent();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsOOPBCurrencyRateAdditiveInPercent($isOOPBCurrencyRateAdditiveInPercent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsOOPBCurrencyRateAdditiveInPercent', array($isOOPBCurrencyRateAdditiveInPercent));

        return parent::setIsOOPBCurrencyRateAdditiveInPercent($isOOPBCurrencyRateAdditiveInPercent);
    }

    /**
     * {@inheritDoc}
     */
    public function getOOPBQuantityUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOOPBQuantityUpdated', array());

        return parent::getOOPBQuantityUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setOOPBQuantityUpdated($OOPBQuantityUpdated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOOPBQuantityUpdated', array($OOPBQuantityUpdated));

        return parent::setOOPBQuantityUpdated($OOPBQuantityUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderOnlyShopTax($orderOnlyShopTax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderOnlyShopTax', array($orderOnlyShopTax));

        return parent::setOrderOnlyShopTax($orderOnlyShopTax);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderOnlyShopTaxInPercent($orderOnlyShopTaxInPercent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderOnlyShopTaxInPercent', array($orderOnlyShopTaxInPercent));

        return parent::setOrderOnlyShopTaxInPercent($orderOnlyShopTaxInPercent);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplier', array());

        return parent::getSupplier();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupplier($supplier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupplier', array($supplier));

        return parent::setSupplier($supplier);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDescriptionSendToYandex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDescriptionSendToYandex', array());

        return parent::getIsDescriptionSendToYandex();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDescriptionSendToYandex($isDescriptionSendToYandex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDescriptionSendToYandex', array($isDescriptionSendToYandex));

        return parent::setIsDescriptionSendToYandex($isDescriptionSendToYandex);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductTags', array());

        return parent::getProductTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductTags($productTags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductTags', array($productTags));

        return parent::setProductTags($productTags);
    }

    /**
     * {@inheritDoc}
     */
    public function addProductTag($productTag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductTag', array($productTag));

        return parent::addProductTag($productTag);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductTag($productTag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductTag', array($productTag));

        return parent::removeProductTag($productTag);
    }

    /**
     * {@inheritDoc}
     */
    public function getYmlCaption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYmlCaption', array());

        return parent::getYmlCaption();
    }

    /**
     * {@inheritDoc}
     */
    public function setYmlCaption($ymlCaption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYmlCaption', array($ymlCaption));

        return parent::setYmlCaption($ymlCaption);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsCanBeInYml()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsCanBeInYml', array());

        return parent::getIsCanBeInYml();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCanBeInYml($isCanBeInYml)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCanBeInYml', array($isCanBeInYml));

        return parent::setIsCanBeInYml($isCanBeInYml);
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', array());

        return parent::preUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function updatePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updatePrice', array());

        return parent::updatePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPhysical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPhysical', array());

        return parent::getIsPhysical();
    }

    /**
     * {@inheritDoc}
     */
    public function isValidCommon(\Symfony\Component\Validator\ExecutionContextInterface $context)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValidCommon', array($context));

        return parent::isValidCommon($context);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaptionRu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaptionRu', array());

        return parent::getCaptionRu();
    }

    /**
     * {@inheritDoc}
     */
    public function getCaptionEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaptionEn', array());

        return parent::getCaptionEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaptionRu($captionRu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaptionRu', array($captionRu));

        return parent::setCaptionRu($captionRu);
    }

    /**
     * {@inheritDoc}
     */
    public function setCaptionEn($captionEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaptionEn', array($captionEn));

        return parent::setCaptionEn($captionEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getShortDescriptionRu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortDescriptionRu', array());

        return parent::getShortDescriptionRu();
    }

    /**
     * {@inheritDoc}
     */
    public function getShortDescriptionEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortDescriptionEn', array());

        return parent::getShortDescriptionEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortDescriptionRu($shortDescriptionRu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortDescriptionRu', array($shortDescriptionRu));

        return parent::setShortDescriptionRu($shortDescriptionRu);
    }

    /**
     * {@inheritDoc}
     */
    public function setShortDescriptionEn($shortDescriptionEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortDescriptionEn', array($shortDescriptionEn));

        return parent::setShortDescriptionEn($shortDescriptionEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionRu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionRu', array());

        return parent::getDescriptionRu();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionEn', array());

        return parent::getDescriptionEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionRu($descriptionRu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionRu', array($descriptionRu));

        return parent::setDescriptionRu($descriptionRu);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionEn($descriptionEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionEn', array($descriptionEn));

        return parent::setDescriptionEn($descriptionEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplectationRu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplectationRu', array());

        return parent::getComplectationRu();
    }

    /**
     * {@inheritDoc}
     */
    public function getComplectationEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplectationEn', array());

        return parent::getComplectationEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplectationRu($complectationRu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplectationRu', array($complectationRu));

        return parent::setComplectationRu($complectationRu);
    }

    /**
     * {@inheritDoc}
     */
    public function setComplectationEn($complectationEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplectationEn', array($complectationEn));

        return parent::setComplectationEn($complectationEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getSloganRu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSloganRu', array());

        return parent::getSloganRu();
    }

    /**
     * {@inheritDoc}
     */
    public function getSloganEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSloganEn', array());

        return parent::getSloganEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setSloganRu($sloganRu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSloganRu', array($sloganRu));

        return parent::setSloganRu($sloganRu);
    }

    /**
     * {@inheritDoc}
     */
    public function setSloganEn($sloganEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSloganEn', array($sloganEn));

        return parent::setSloganEn($sloganEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleRu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleRu', array());

        return parent::getTitleRu();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleEn', array());

        return parent::getTitleEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleRu($titleRu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleRu', array($titleRu));

        return parent::setTitleRu($titleRu);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleEn($titleEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleEn', array($titleEn));

        return parent::setTitleEn($titleEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetakeywordsRu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetakeywordsRu', array());

        return parent::getMetakeywordsRu();
    }

    /**
     * {@inheritDoc}
     */
    public function getMetakeywordsEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetakeywordsEn', array());

        return parent::getMetakeywordsEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetakeywordsRu($metakeywordsRu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetakeywordsRu', array($metakeywordsRu));

        return parent::setMetakeywordsRu($metakeywordsRu);
    }

    /**
     * {@inheritDoc}
     */
    public function setMetakeywordsEn($metakeywordsEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetakeywordsEn', array($metakeywordsEn));

        return parent::setMetakeywordsEn($metakeywordsEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetadescriptionRu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetadescriptionRu', array());

        return parent::getMetadescriptionRu();
    }

    /**
     * {@inheritDoc}
     */
    public function getMetadescriptionEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetadescriptionEn', array());

        return parent::getMetadescriptionEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetadescriptionRu($metadescriptionRu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetadescriptionRu', array($metadescriptionRu));

        return parent::setMetadescriptionRu($metadescriptionRu);
    }

    /**
     * {@inheritDoc}
     */
    public function setMetadescriptionEn($metadescriptionEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetadescriptionEn', array($metadescriptionEn));

        return parent::setMetadescriptionEn($metadescriptionEn);
    }

    /**
     * {@inheritDoc}
     */
    public function setCaptionCaseEn($captionCaseEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaptionCaseEn', array($captionCaseEn));

        return parent::setCaptionCaseEn($captionCaseEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaptionCaseEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaptionCaseEn', array());

        return parent::getCaptionCaseEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaptionCaseRu($captionCaseRu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaptionCaseRu', array($captionCaseRu));

        return parent::setCaptionCaseRu($captionCaseRu);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaptionCaseRu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaptionCaseRu', array());

        return parent::getCaptionCaseRu();
    }

    /**
     * {@inheritDoc}
     */
    public function getNetWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetWeight', array());

        return parent::getNetWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetWeight($netWeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetWeight', array($netWeight));

        return parent::setNetWeight($netWeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsNetWeightInGm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsNetWeightInGm', array());

        return parent::getIsNetWeightInGm();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsNetWeightInGm($isNetWeightInGm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsNetWeightInGm', array($isNetWeightInGm));

        return parent::setIsNetWeightInGm($isNetWeightInGm);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrossWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrossWeight', array());

        return parent::getGrossWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrossWeight($grossWeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrossWeight', array($grossWeight));

        return parent::setGrossWeight($grossWeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsGrossWeightInGm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsGrossWeightInGm', array());

        return parent::getIsGrossWeightInGm();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsGrossWeightInGm($isGrossWeightInGm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsGrossWeightInGm', array($isGrossWeightInGm));

        return parent::setIsGrossWeightInGm($isGrossWeightInGm);
    }

    /**
     * {@inheritDoc}
     */
    public function getLengthOfProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLengthOfProduct', array());

        return parent::getLengthOfProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setLengthOfProduct($lengthOfProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLengthOfProduct', array($lengthOfProduct));

        return parent::setLengthOfProduct($lengthOfProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidthOfProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidthOfProduct', array());

        return parent::getWidthOfProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidthOfProduct($widthOfProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidthOfProduct', array($widthOfProduct));

        return parent::setWidthOfProduct($widthOfProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeightOfProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeightOfProduct', array());

        return parent::getHeightOfProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeightOfProduct($heightOfProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeightOfProduct', array($heightOfProduct));

        return parent::setHeightOfProduct($heightOfProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getLengthOfBox()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLengthOfBox', array());

        return parent::getLengthOfBox();
    }

    /**
     * {@inheritDoc}
     */
    public function setLengthOfBox($lengthOfBox)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLengthOfBox', array($lengthOfBox));

        return parent::setLengthOfBox($lengthOfBox);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidthOfBox()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidthOfBox', array());

        return parent::getWidthOfBox();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidthOfBox($widthOfBox)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidthOfBox', array($widthOfBox));

        return parent::setWidthOfBox($widthOfBox);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeightOfBox()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeightOfBox', array());

        return parent::getHeightOfBox();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeightOfBox($heightOfBox)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeightOfBox', array($heightOfBox));

        return parent::setHeightOfBox($heightOfBox);
    }

    /**
     * {@inheritDoc}
     */
    public function isValidProduct(\Symfony\Component\Validator\ExecutionContextInterface $context)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValidProduct', array($context));

        return parent::isValidProduct($context);
    }

}
