<?php

namespace Proxies\__CG__\Core\PropertyBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DataProperty extends \Core\PropertyBundle\Entity\DataProperty implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'id', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'property', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'productDataProperty', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'value', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'name', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'indexPosition', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'shortDescription', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'articleKey', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'isEnabled');
        }

        return array('__isInitialized__', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'id', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'property', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'productDataProperty', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'value', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'name', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'indexPosition', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'shortDescription', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'articleKey', '' . "\0" . 'Core\\PropertyBundle\\Entity\\DataProperty' . "\0" . 'isEnabled');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DataProperty $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProperty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProperty', array());

        return parent::getProperty();
    }

    /**
     * {@inheritDoc}
     */
    public function setProperty($property)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProperty', array($property));

        return parent::setProperty($property);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductDataProperty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductDataProperty', array());

        return parent::getProductDataProperty();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductDataProperty($productDataProperty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductDataProperty', array($productDataProperty));

        return parent::setProductDataProperty($productDataProperty);
    }

    /**
     * {@inheritDoc}
     */
    public function getValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValue', array());

        return parent::getValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setValue($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValue', array($value));

        return parent::setValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexPosition', array());

        return parent::getIndexPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndexPosition($indexPosition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndexPosition', array($indexPosition));

        return parent::setIndexPosition($indexPosition);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsEnabled', array());

        return parent::getIsEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsEnabled($isEnabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsEnabled', array($isEnabled));

        return parent::setIsEnabled($isEnabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getDynamicFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDynamicFields', array());

        return parent::getDynamicFields();
    }

    /**
     * {@inheritDoc}
     */
    public function getShortDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortDescription', array());

        return parent::getShortDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortDescription($shortDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortDescription', array($shortDescription));

        return parent::setShortDescription($shortDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticleKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticleKey', array());

        return parent::getArticleKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticleKey($articleKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticleKey', array($articleKey));

        return parent::setArticleKey($articleKey);
    }

}
