<?php

namespace Proxies\__CG__\Core\OrderBundle\Entity\PreOrder;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PreOrder extends \Core\OrderBundle\Entity\PreOrder\PreOrder implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'id', 'email', 'phone', 'address', 'firstName', 'lastName', 'surName', 'city', 'contragent', 'user', 'status', 'order', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'createdDateTime', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'adminComments', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'subscribersOnAdminComments', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'cancelReason', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'isSendCancelMsg', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'compositions', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'isVisible');
        }

        return array('__isInitialized__', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'id', 'email', 'phone', 'address', 'firstName', 'lastName', 'surName', 'city', 'contragent', 'user', 'status', 'order', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'createdDateTime', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'adminComments', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'subscribersOnAdminComments', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'cancelReason', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'isSendCancelMsg', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'compositions', '' . "\0" . 'Core\\OrderBundle\\Entity\\PreOrder\\PreOrder' . "\0" . 'isVisible');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PreOrder $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDone', array());

        return parent::getIsDone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDone($isDone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDone', array($isDone));

        return parent::setIsDone($isDone);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDateTime', array());

        return parent::getCreatedDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDateTime($createdDateTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDateTime', array($createdDateTime));

        return parent::setCreatedDateTime($createdDateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($firstName));

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', array($lastName));

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurName', array());

        return parent::getSurName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurName($surName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurName', array($surName));

        return parent::setSurName($surName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(\Core\DirectoryBundle\Entity\City $city = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(\Core\OrderBundle\Entity\PreOrder\PreOrderStatus $status = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getContragent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContragent', array());

        return parent::getContragent();
    }

    /**
     * {@inheritDoc}
     */
    public function setContragent(\Application\Sonata\UserBundle\Entity\CommonContragent $contragent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContragent', array($contragent));

        return parent::setContragent($contragent);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Application\Sonata\UserBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', array());

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder(\Core\OrderBundle\Entity\Order $order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', array($order));

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullName', array());

        return parent::getFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminComments', array());

        return parent::getAdminComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminComments($adminComments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminComments', array($adminComments));

        return parent::setAdminComments($adminComments);
    }

    /**
     * {@inheritDoc}
     */
    public function addAdminComments($adminComments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdminComments', array($adminComments));

        return parent::addAdminComments($adminComments);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdminComments($adminComments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdminComments', array($adminComments));

        return parent::removeAdminComments($adminComments);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubscribersOnAdminComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubscribersOnAdminComments', array());

        return parent::getSubscribersOnAdminComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubscribersOnAdminComments($subscribersOnAdminComments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubscribersOnAdminComments', array($subscribersOnAdminComments));

        return parent::setSubscribersOnAdminComments($subscribersOnAdminComments);
    }

    /**
     * {@inheritDoc}
     */
    public function addSubscribersOnAdminComments($subscribersOnAdminComments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSubscribersOnAdminComments', array($subscribersOnAdminComments));

        return parent::addSubscribersOnAdminComments($subscribersOnAdminComments);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSubscribersOnAdminComments($subscribersOnAdminComments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSubscribersOnAdminComments', array($subscribersOnAdminComments));

        return parent::removeSubscribersOnAdminComments($subscribersOnAdminComments);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullAddress', array());

        return parent::getFullAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getCancelReason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCancelReason', array());

        return parent::getCancelReason();
    }

    /**
     * {@inheritDoc}
     */
    public function setCancelReason($cancelReason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCancelReason', array($cancelReason));

        return parent::setCancelReason($cancelReason);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSendCancelMsg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsSendCancelMsg', array());

        return parent::getIsSendCancelMsg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSendCancelMsg($isSendCancelMsg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSendCancelMsg', array($isSendCancelMsg));

        return parent::setIsSendCancelMsg($isSendCancelMsg);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompositions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompositions', array());

        return parent::getCompositions();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompositions($compositions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompositions', array($compositions));

        return parent::setCompositions($compositions);
    }

    /**
     * {@inheritDoc}
     */
    public function addComposition($composition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComposition', array($composition));

        return parent::addComposition($composition);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComposition($composition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComposition', array($composition));

        return parent::removeComposition($composition);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsVisible', array());

        return parent::getIsVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsVisible($isVisible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsVisible', array($isVisible));

        return parent::setIsVisible($isVisible);
    }

    /**
     * {@inheritDoc}
     */
    public function getFio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFio', array());

        return parent::getFio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFio($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFio', array($value));

        return parent::setFio($value);
    }

    /**
     * {@inheritDoc}
     */
    public function isValid(\Symfony\Component\Validator\ExecutionContextInterface $context)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValid', array($context));

        return parent::isValid($context);
    }

}
