<?php

/**
 * Репозиторий для работы с сущностью IndiContact
 *
 * @author  Sergeev A.M.
 * @copyright LLC "PromoMaster"
 */

namespace Application\Sonata\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IndiContragentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndiContactRepository extends EntityRepository
{
    /**
     * Контрагент со всеми адресатами
     * @param int $id
     * @return type
     */
    public function findWithContact($id)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c, contact, city')
           ->leftJoin('c.contactList', 'contact')
           ->leftJoin('contact.city', 'city')
           ->where('c.id = :id')
        ;
        $qb->setParameter('id', $id);

        $result = $qb->getQuery()->getOneOrNullResult();

        return $result;
    }
}
