<?php

namespace Core\CommonBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FragmentsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\CommonBundle\Controller\FragmentsController();
        return $instance;
    }
}
