<?php

namespace Core\HolidayBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class HolidayAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\HolidayBundle\Controller\Admin\HolidayAdminController();
        return $instance;
    }
}
