<?php

namespace Core\ProductBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdminProductController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\ProductBundle\Controller\Admin\AdminProductController();
        return $instance;
    }
}
