<?php

namespace Core\TroubleTicketBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PriorityAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\TroubleTicketBundle\Controller\Admin\PriorityAdminController();
        return $instance;
    }
}
