<?php

namespace Core\DeliveryBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DeliveryController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\DeliveryBundle\Controller\DeliveryController();
        return $instance;
    }
}
