<?php

namespace Core\PaymentBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PaymentAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\PaymentBundle\Controller\Admin\PaymentAdminController();
        return $instance;
    }
}
