<?php

namespace Core\LanguageBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class LanguageController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\LanguageBundle\Controller\LanguageController();
        return $instance;
    }
}
