<?php

namespace Proxies\__CG__\Core\LogisticsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Stock extends \Core\LogisticsBundle\Entity\Stock implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'city', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'address', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'phone', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'workTimeStart', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'workTimeEnd', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'isGeneralStock', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'regionsCityList', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'units', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'code', 'captionRu', 'captionEn');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'city', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'address', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'phone', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'workTimeStart', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'workTimeEnd', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'isGeneralStock', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'regionsCityList', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'units', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\Stock' . "\0" . 'code', 'captionRu', 'captionEn');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Stock $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkTimeStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkTimeStart', array());

        return parent::getWorkTimeStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkTimeStart($workTimeStart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkTimeStart', array($workTimeStart));

        return parent::setWorkTimeStart($workTimeStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkTimeEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkTimeEnd', array());

        return parent::getWorkTimeEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkTimeEnd($workTimeEnd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkTimeEnd', array($workTimeEnd));

        return parent::setWorkTimeEnd($workTimeEnd);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsGeneralStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsGeneralStock', array());

        return parent::getIsGeneralStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsGeneralStock($isGeneralStock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsGeneralStock', array($isGeneralStock));

        return parent::setIsGeneralStock($isGeneralStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegionsCityList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegionsCityList', array());

        return parent::getRegionsCityList();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegionsCityList($regionsCityList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegionsCityList', array($regionsCityList));

        return parent::setRegionsCityList($regionsCityList);
    }

    /**
     * {@inheritDoc}
     */
    public function addRegionsCityList($regionsCityList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRegionsCityList', array($regionsCityList));

        return parent::addRegionsCityList($regionsCityList);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRegionsCityList($regionsCityList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRegionsCityList', array($regionsCityList));

        return parent::removeRegionsCityList($regionsCityList);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnits', array());

        return parent::getUnits();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnits($units)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnits', array($units));

        return parent::setUnits($units);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', array());

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaptionRu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaptionRu', array());

        return parent::getCaptionRu();
    }

    /**
     * {@inheritDoc}
     */
    public function getCaptionEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaptionEn', array());

        return parent::getCaptionEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaptionRu($captionRu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaptionRu', array($captionRu));

        return parent::setCaptionRu($captionRu);
    }

    /**
     * {@inheritDoc}
     */
    public function setCaptionEn($captionEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaptionEn', array($captionEn));

        return parent::setCaptionEn($captionEn);
    }

}
