<?php

namespace Proxies\__CG__\Core\PropertyBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Property extends \Core\PropertyBundle\Entity\Property implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'id', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'editType', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'categories', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'createdDateTime', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'name', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'dataList', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'settingsCategory', 'captionRu', 'captionEn', 'descriptionRu', 'descriptionEn');
        }

        return array('__isInitialized__', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'id', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'editType', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'categories', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'createdDateTime', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'name', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'dataList', '' . "\0" . 'Core\\PropertyBundle\\Entity\\Property' . "\0" . 'settingsCategory', 'captionRu', 'captionEn', 'descriptionRu', 'descriptionEn');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Property $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getEditType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditType', array());

        return parent::getEditType();
    }

    /**
     * {@inheritDoc}
     */
    public function setEditType($editType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEditType', array($editType));

        return parent::setEditType($editType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', array());

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategories($categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategories', array($categories));

        return parent::setCategories($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDateTime', array());

        return parent::getCreatedDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDateTime($createdDateTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDateTime', array($createdDateTime));

        return parent::setCreatedDateTime($createdDateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaptionRu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaptionRu', array());

        return parent::getCaptionRu();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaptionRu($captionRu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaptionRu', array($captionRu));

        return parent::setCaptionRu($captionRu);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionRu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionRu', array());

        return parent::getDescriptionRu();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionRu($descriptionRu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionRu', array($descriptionRu));

        return parent::setDescriptionRu($descriptionRu);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataList', array());

        return parent::getDataList();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataList($dataList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataList', array($dataList));

        return parent::setDataList($dataList);
    }

    /**
     * {@inheritDoc}
     */
    public function addDataList(\Core\PropertyBundle\Entity\DataProperty $dataList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDataList', array($dataList));

        return parent::addDataList($dataList);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDataList(\Core\PropertyBundle\Entity\DataProperty $dataList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDataList', array($dataList));

        return parent::removeDataList($dataList);
    }

    /**
     * {@inheritDoc}
     */
    public function getSettingsCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSettingsCategory', array());

        return parent::getSettingsCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setSettingsCategory(\Doctrine\Common\Collections\ArrayCollection $settingsCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSettingsCategory', array($settingsCategory));

        return parent::setSettingsCategory($settingsCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeneralSettingsCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeneralSettingsCategory', array());

        return parent::getGeneralSettingsCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultValue', array());

        return parent::getDefaultValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultValue($defaultValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultValue', array($defaultValue));

        return parent::setDefaultValue($defaultValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsEnabled', array());

        return parent::getIsEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsEnabled($isEnabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsEnabled', array($isEnabled));

        return parent::setIsEnabled($isEnabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsGeneral()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsGeneral', array());

        return parent::getIsGeneral();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsGeneral($isGeneral)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsGeneral', array($isGeneral));

        return parent::setIsGeneral($isGeneral);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsUsedInFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsUsedInFilter', array());

        return parent::getIsUsedInFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsUsedInFilter($isUsedInFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsUsedInFilter', array($isUsedInFilter));

        return parent::setIsUsedInFilter($isUsedInFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRequired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRequired', array());

        return parent::getIsRequired();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRequired($isRequired)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRequired', array($isRequired));

        return parent::setIsRequired($isRequired);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultUnit', array());

        return parent::getDefaultUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultUnit($defaultUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultUnit', array($defaultUnit));

        return parent::setDefaultUnit($defaultUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getMask()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMask', array());

        return parent::getMask();
    }

    /**
     * {@inheritDoc}
     */
    public function setMask($mask)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMask', array($mask));

        return parent::setMask($mask);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexPosition', array());

        return parent::getIndexPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndexPosition($indexPosition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndexPosition', array($indexPosition));

        return parent::setIndexPosition($indexPosition);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsEnabledInYml()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsEnabledInYml', array());

        return parent::getIsEnabledInYml();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsEnabledInYml($isEnabledInYml)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsEnabledInYml', array($isEnabledInYml));

        return parent::setIsEnabledInYml($isEnabledInYml);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaptionEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaptionEn', array());

        return parent::getCaptionEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaptionEn($captionEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaptionEn', array($captionEn));

        return parent::setCaptionEn($captionEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionEn', array());

        return parent::getDescriptionEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionEn($descriptionEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionEn', array($descriptionEn));

        return parent::setDescriptionEn($descriptionEn);
    }

}
