# Вывод первой страницы списка рекламных компаний в личном кабинете
core_cabinet_adcompany_list_first_page:
    path:      /cabinet/adcompanies.html
    schemes:  [http]
    defaults:  { _controller: CoreAdCompanyBundle:AdCompanyCabinet:list}

# Вывод списка рекламных компаний в ЛК
core_cabinet_adcompany_list:
    path:      /cabinet/adcompanies/{page}.html
    schemes:  [http]
    defaults:  { _controller: CoreAdCompanyBundle:AdCompanyCabinet:list, page: 1 }
    requirements:
      page: \d+

# редактирование рекламной компании в ЛК
core_cabinet_adcompany_edit:
    path:      /cabinet/adcompany_edit_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreAdCompanyBundle:AdCompanyCabinet:edit }
    requirements:
      id: \d+


# добавление сайта в ЛК
core_cabinet_adcompany_create:
    path:      /cabinet/adcompany_create.html
    schemes:  [http]
    defaults:  { _controller: CoreAdCompanyBundle:AdCompanyCabinet:create }


# удаление рекламной компании в ЛК
core_cabinet_adcompany_delete:
    path:      /cabinet/adcompany_delete_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreAdCompanyBundle:AdCompanyCabinet:delete }
    requirements:
      id: \d+


core_cabinet_set_adcompany_status:
    path:      /cabinet/adcompany/setstatus/{id}/{status}/{page}.html
    schemes:  [http]
    defaults:  { _controller: CoreAdCompanyBundle:AdCompanyCabinet:setStatus }
    requirements:
      id: \d+
      page: \d+
      status: on|off