# Вывод первой страницы списка размещений в личном кабинете
core_cabinet_placement_list_first_page:
    path:      /cabinet/placements.html
    schemes:  [http]
    defaults:  { _controller: CoreAdCompanyBundle:PlacementCabinet:list}

# Вывод списка размещений в ЛК
core_cabinet_placement_list:
    path:      /cabinet/placements/{page}.html
    schemes:  [http]
    defaults:  { _controller: CoreAdCompanyBundle:PlacementCabinet:list, page: 1 }
    requirements:
      page: \d+

# редактирование размещения в ЛК
core_cabinet_placement_edit:
    path:      /cabinet/placement_edit_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreAdCompanyBundle:PlacementCabinet:edit }
    requirements:
      id: \d+


# добавление размещения в ЛК
core_cabinet_placement_create:
    path:      /cabinet/placement_create.html
    schemes:  [http]
    defaults:  { _controller: CoreAdCompanyBundle:PlacementCabinet:create }


# удаление размещения в ЛК
core_cabinet_placement_delete:
    path:      /cabinet/placement_delete_{id}.html
    schemes:  [http]
    defaults:  { _controller: CoreAdCompanyBundle:PlacementCabinet:delete }
    requirements:
      id: \d+
