services:
  #админсике классы для рекламных компаний
  core_ad_company_admin:
    class: Core\AdCompanyBundle\Admin\AdCompanyAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore,  group: Материалы, label: Рекламные компании }
    arguments: [null, Core\AdCompanyBundle\Entity\AdCompany, null]


  #админсике классы для размещений
  core_placement_admin:
    class: Core\AdCompanyBundle\Admin\PlacementAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore,  group: Материалы, label: Размещения }
    arguments: [null, Core\AdCompanyBundle\Entity\Placement, null]


#админсике классы для баннеров размещения
  core_placement_banner_admin:
    class: Core\AdCompanyBundle\Admin\PlacementBannerAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, audit: false, label_translator_strategy: sonata.admin.label.strategy.underscore,  group: Материалы, label: Баннеры размещения }
    arguments: [null, Core\AdCompanyBundle\Entity\PlacementBanner, null]


# логика для размещений
  core_placement_logic:
    class: Core\AdCompanyBundle\Logic\PlacementLogic
    arguments: ['@router', '@doctrine.orm.entity_manager', '@service_container', '@application_knp_paginator_logic']

# логика для рекламных компаний
  core_adcompany_logic:
    class: Core\AdCompanyBundle\Logic\AdCompanyLogic
    arguments: ['@router', '@doctrine.orm.entity_manager', '@service_container', '@application_knp_paginator_logic', '@core_placement_logic']



# подписчик для РК
  core_adcompany_subscriber:
    class: Core\AdCompanyBundle\EventListener\AdCompanySubscriber
    tags:
        - { name: doctrine.event_subscriber }
