<?php

namespace Proxies\__CG__\Core\OrderBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SizesOfBox extends \Core\OrderBundle\Entity\SizesOfBox implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'height', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'length', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'width', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'weight', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'isWeightInKg', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'waybill', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'indexPosition');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'height', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'length', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'width', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'weight', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'isWeightInKg', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'waybill', '' . "\0" . 'Core\\OrderBundle\\Entity\\SizesOfBox' . "\0" . 'indexPosition');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SizesOfBox $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeight', array());

        return parent::getHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeight($height)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeight', array($height));

        return parent::setHeight($height);
    }

    /**
     * {@inheritDoc}
     */
    public function getLength()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLength', array());

        return parent::getLength();
    }

    /**
     * {@inheritDoc}
     */
    public function setLength($length)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLength', array($length));

        return parent::setLength($length);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidth', array());

        return parent::getWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidth($width)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidth', array($width));

        return parent::setWidth($width);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeight', array());

        return parent::getWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeight($weight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeight', array($weight));

        return parent::setWeight($weight);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsWeightInKg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsWeightInKg', array());

        return parent::getIsWeightInKg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsWeightInKg($isWeightInKg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsWeightInKg', array($isWeightInKg));

        return parent::setIsWeightInKg($isWeightInKg);
    }

    /**
     * {@inheritDoc}
     */
    public function getWaybill()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWaybill', array());

        return parent::getWaybill();
    }

    /**
     * {@inheritDoc}
     */
    public function setWaybill(\Core\OrderBundle\Entity\Waybills $waybill = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWaybill', array($waybill));

        return parent::setWaybill($waybill);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexPosition', array());

        return parent::getIndexPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndexPosition($indexPosition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndexPosition', array($indexPosition));

        return parent::setIndexPosition($indexPosition);
    }

}
