<?php

namespace Proxies\__CG__\Core\DiscountsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ContragentManufacturerStepValues extends \Core\DiscountsBundle\Entity\ContragentManufacturerStepValues implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'Core\\DiscountsBundle\\Entity\\ContragentManufacturerStepValues' . "\0" . 'manufacturerDiscount', '' . "\0" . 'Core\\DiscountsBundle\\Entity\\ContragentManufacturerStepValues' . "\0" . 'stepValue', '' . "\0" . 'Core\\DiscountsBundle\\Entity\\ContragentManufacturerStepValues' . "\0" . 'discountValue', '' . "\0" . 'Core\\DiscountsBundle\\Entity\\ContragentManufacturerStepValues' . "\0" . 'isDiscountValueInPercent', '' . "\0" . 'Core\\DiscountsBundle\\Entity\\ContragentManufacturerStepValues' . "\0" . 'createdDateTime', '' . "\0" . 'Core\\DiscountsBundle\\Entity\\ContragentManufacturerStepValues' . "\0" . 'indexPosition');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'Core\\DiscountsBundle\\Entity\\ContragentManufacturerStepValues' . "\0" . 'manufacturerDiscount', '' . "\0" . 'Core\\DiscountsBundle\\Entity\\ContragentManufacturerStepValues' . "\0" . 'stepValue', '' . "\0" . 'Core\\DiscountsBundle\\Entity\\ContragentManufacturerStepValues' . "\0" . 'discountValue', '' . "\0" . 'Core\\DiscountsBundle\\Entity\\ContragentManufacturerStepValues' . "\0" . 'isDiscountValueInPercent', '' . "\0" . 'Core\\DiscountsBundle\\Entity\\ContragentManufacturerStepValues' . "\0" . 'createdDateTime', '' . "\0" . 'Core\\DiscountsBundle\\Entity\\ContragentManufacturerStepValues' . "\0" . 'indexPosition');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ContragentManufacturerStepValues $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturerDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturerDiscount', array());

        return parent::getManufacturerDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setManufacturerDiscount($manufacturerDiscount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManufacturerDiscount', array($manufacturerDiscount));

        return parent::setManufacturerDiscount($manufacturerDiscount);
    }

    /**
     * {@inheritDoc}
     */
    public function getStepValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStepValue', array());

        return parent::getStepValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setStepValue($stepValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStepValue', array($stepValue));

        return parent::setStepValue($stepValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountValue', array());

        return parent::getDiscountValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountValue($discountValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountValue', array($discountValue));

        return parent::setDiscountValue($discountValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDiscountValueInPercent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDiscountValueInPercent', array());

        return parent::getIsDiscountValueInPercent();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDiscountValueInPercent($isDiscountValueInPercent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDiscountValueInPercent', array($isDiscountValueInPercent));

        return parent::setIsDiscountValueInPercent($isDiscountValueInPercent);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDateTime', array());

        return parent::getCreatedDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDateTime($createdDateTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDateTime', array($createdDateTime));

        return parent::setCreatedDateTime($createdDateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexPosition', array());

        return parent::getIndexPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndexPosition($indexPosition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndexPosition', array($indexPosition));

        return parent::setIndexPosition($indexPosition);
    }

}
