<?php

namespace Proxies\__CG__\Core\LogisticsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SupplierPriceAnalysisSettings extends \Core\LogisticsBundle\Entity\SupplierPriceAnalysisSettings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\SupplierPriceAnalysisSettings' . "\0" . 'id', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\SupplierPriceAnalysisSettings' . "\0" . 'supplier', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\SupplierPriceAnalysisSettings' . "\0" . 'columnCaption', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\SupplierPriceAnalysisSettings' . "\0" . 'fieldNameFromProductEntity', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\SupplierPriceAnalysisSettings' . "\0" . 'fieldType', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\SupplierPriceAnalysisSettings' . "\0" . 'indexPosition');
        }

        return array('__isInitialized__', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\SupplierPriceAnalysisSettings' . "\0" . 'id', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\SupplierPriceAnalysisSettings' . "\0" . 'supplier', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\SupplierPriceAnalysisSettings' . "\0" . 'columnCaption', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\SupplierPriceAnalysisSettings' . "\0" . 'fieldNameFromProductEntity', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\SupplierPriceAnalysisSettings' . "\0" . 'fieldType', '' . "\0" . 'Core\\LogisticsBundle\\Entity\\SupplierPriceAnalysisSettings' . "\0" . 'indexPosition');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SupplierPriceAnalysisSettings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplier', array());

        return parent::getSupplier();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupplier($supplier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupplier', array($supplier));

        return parent::setSupplier($supplier);
    }

    /**
     * {@inheritDoc}
     */
    public function getColumnCaption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColumnCaption', array());

        return parent::getColumnCaption();
    }

    /**
     * {@inheritDoc}
     */
    public function setColumnCaption($columnCaption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColumnCaption', array($columnCaption));

        return parent::setColumnCaption($columnCaption);
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldNameFromProductEntity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldNameFromProductEntity', array());

        return parent::getFieldNameFromProductEntity();
    }

    /**
     * {@inheritDoc}
     */
    public function setFieldNameFromProductEntity($fieldNameFromProductEntity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFieldNameFromProductEntity', array($fieldNameFromProductEntity));

        return parent::setFieldNameFromProductEntity($fieldNameFromProductEntity);
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldType', array());

        return parent::getFieldType();
    }

    /**
     * {@inheritDoc}
     */
    public function setFieldType($fieldType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFieldType', array($fieldType));

        return parent::setFieldType($fieldType);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexPosition', array());

        return parent::getIndexPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndexPosition($indexPosition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndexPosition', array($indexPosition));

        return parent::setIndexPosition($indexPosition);
    }

}
